import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { Keypair, PublicKey, VersionedTransaction } from '@solana/web3.js';
import { discoverRecoverAccounts, inspectRecoverWrappedSol, recoverSourceAccount } from '../chains/solana/recover/accounts.js';
import { evaluateRecoverApprovalDelay, RECOVER_PRE_WALLET_MINIMUM_BLOCK_MARGIN } from '../chains/solana/recover/validity.js';
import { buildRecoverTransaction, calculateRecoverFees, calculateRecoverMinimumPayout } from '../chains/solana/transactions/recover.js';
import { LEGACY_TOKEN_PROGRAM_ID, TOKEN_2022_PROGRAM_ID } from '../chains/solana/claim/accounts.js';
import { EmergencyControlService } from '../server/controls/service.js';
import { GaslessError } from '../server/errors.js';
import { ASSOCIATED_TOKEN_PROGRAM_ID, COMPUTE_BUDGET_PROGRAM_ID, JUPITER_SWAP_PROGRAM_ID, JupiterService, RAYDIUM_CLMM_PROGRAM_ID, WRAPPED_SOL_MINT, wrappedSolAccount, type JupiterBuild, type JupiterRouter } from '../server/jupiter/service.js';
import { RecoverEngine } from '../server/recover/engine.js';
import { LocalDevnetRelayerProvider } from '../server/relayer/provider.js';
import type { RpcAccountInfo, SolanaRpc } from '../server/solana/rpc.js';
import { MemoryDurableStore } from '../server/storage/durable.js';
import { MemoryTemporaryStore } from '../server/storage/temporary.js';
import { ServerTokenRegistry } from '../server/token-registry/service.js';
import { recoverHasEconomicDownside } from '../src/features/clean/recoverLifecycle.js';
import type { RecoverQuoteDetails } from '../shared/transactions/types.js';

function mintAccount(program = LEGACY_TOKEN_PROGRAM_ID): RpcAccountInfo { const data = Buffer.alloc(82); data.writeBigUInt64LE(1_000_000_000n, 36); data[44] = 6; data[45] = 1; return { lamports: 1_461_600, owner: program, executable: false, rentEpoch: 0, data: [data.toString('base64'), 'base64'] }; }
function tokenAccount(wallet: PublicKey, mint: PublicKey, options: { amount?: bigint; program?: string; delegate?: boolean } = {}): RpcAccountInfo { const data = Buffer.alloc(165); mint.toBuffer().copy(data, 0); wallet.toBuffer().copy(data, 32); data.writeBigUInt64LE(options.amount ?? 123_456_789n, 64); data.writeUInt32LE(options.delegate ? 1 : 0, 72); data[108] = 1; data.writeBigUInt64LE(options.delegate ? 1n : 0n, 121); return { lamports: 2_039_280, owner: options.program ?? LEGACY_TOKEN_PROGRAM_ID, executable: false, rentEpoch: 0, data: [data.toString('base64'), 'base64'] }; }

function buildRoute(wallet: string, payer: string, account: string, mint: string): JupiterBuild { const hash = Keypair.generate().publicKey.toBytes(); const wrapped = wrappedSolAccount(wallet); return { inputMint: mint, outputMint: WRAPPED_SOL_MINT, inAmount: '123456789', outAmount: '1010000000', otherAmountThreshold: '1000000000', swapMode: 'ExactIn', slippageBps: 50, routePlan: [{ swapInfo: { label: 'Raydium CLMM', inputMint: mint, outputMint: WRAPPED_SOL_MINT, inAmount: '123456789', outAmount: '1010000000' }, bps: 10_000 }], computeBudgetInstructions: [{ programId: COMPUTE_BUDGET_PROGRAM_ID, accounts: [], data: Buffer.from([3, 1, 0, 0, 0, 0, 0, 0, 0]).toString('base64') }], setupInstructions: [{ programId: ASSOCIATED_TOKEN_PROGRAM_ID, accounts: [{ pubkey: payer, isSigner: true, isWritable: true }, { pubkey: wrapped, isSigner: false, isWritable: true }, { pubkey: wallet, isSigner: false, isWritable: false }, { pubkey: WRAPPED_SOL_MINT, isSigner: false, isWritable: false }, { pubkey: '11111111111111111111111111111111', isSigner: false, isWritable: false }, { pubkey: LEGACY_TOKEN_PROGRAM_ID, isSigner: false, isWritable: false }], data: Buffer.from([1]).toString('base64') }], swapInstruction: { programId: JUPITER_SWAP_PROGRAM_ID, accounts: [{ pubkey: wallet, isSigner: true, isWritable: true }, { pubkey: payer, isSigner: true, isWritable: true }, { pubkey: account, isSigner: false, isWritable: true }, { pubkey: wrapped, isSigner: false, isWritable: true }, { pubkey: RAYDIUM_CLMM_PROGRAM_ID, isSigner: false, isWritable: false }], data: Buffer.from([1, 2, 3]).toString('base64') }, cleanupInstruction: { programId: LEGACY_TOKEN_PROGRAM_ID, accounts: [{ pubkey: wrapped, isSigner: false, isWritable: true }, { pubkey: wallet, isSigner: false, isWritable: true }, { pubkey: wallet, isSigner: true, isWritable: false }], data: Buffer.from([9]).toString('base64') }, otherInstructions: [], tipInstruction: null, addressesByLookupTableAddress: {}, blockhashWithMetadata: { blockhash: [...hash], lastValidBlockHeight: 200 } }; }

class FakeRecoverRpc {
  readonly mint = Keypair.generate().publicKey; readonly tokenAddress: string; readonly token: RpcAccountInfo; sent?: string; fee = 530_000; blockHeight = 10; simulations = 0; failFinal = false; mismatchPayout = false; statusMode: 'confirmed' | 'pending' | 'expired' | 'chain_error' = 'confirmed'; broadcastCalls = 0;
  constructor(readonly wallet: Keypair) { this.tokenAddress = recoverSourceAccount(wallet.publicKey.toBase58(), this.mint.toBase58()); this.token = tokenAccount(wallet.publicKey, this.mint); }
  async getTokenAccountsByOwner(_owner: string, program: string) { return program === LEGACY_TOKEN_PROGRAM_ID ? [{ pubkey: this.tokenAddress, account: this.token }] : []; }
  async getMultipleAccounts(addresses: string[]) { return addresses.map((address) => address === this.tokenAddress ? this.token : address === this.mint.toBase58() ? mintAccount() : null); }
  async getAccountInfo(address: string) { return address === this.tokenAddress && !this.sent ? this.token : null; }
  async getMinimumBalanceForRentExemption() { return 2_039_280; }
  async getBlockHeight() { return this.blockHeight; } async getFeeForMessage() { return this.fee; }
  async simulateTransaction() { this.simulations += 1; return { err: this.failFinal && this.simulations > 2 ? { failed: true } : null, logs: ['ok'], unitsConsumed: 200_000, provider: 'fake' }; }
  async getBalance() { return 10_000_000; } async sendRawTransaction(serialized: string) { this.sent = serialized; return { signature: 'recover-devnet-signature', provider: 'fake' }; }
  async getSignatureStatuses() { return { slot: 8, confirmations: 1, err: null, confirmationStatus: 'confirmed' }; }
  async getBlockHeightsAcrossProviders() { return [{ provider: 'fake', value: this.statusMode === 'expired' ? 201 : this.blockHeight }]; }
  async broadcastRawTransactionAcrossProviders(serialized: string) { this.broadcastCalls += 1; this.sent = serialized; return [{ provider: 'fake', category: 'accepted' as const }]; }
  async getSignatureStatusesAcrossProviders() { if (this.statusMode === 'confirmed') return [{ provider: 'fake', value: { slot: 8, confirmations: 1, err: null, confirmationStatus: 'confirmed' } }]; if (this.statusMode === 'chain_error') return [{ provider: 'fake', value: { slot: 8, confirmations: 1, err: { failed: true }, confirmationStatus: 'confirmed' } }]; return [{ provider: 'fake', value: null }]; }
  async getTransactionAcrossProviders() { return this.getTransaction(); }
  async getTransaction() { const transaction = VersionedTransaction.deserialize(Buffer.from(this.sent!, 'base64')); const keys = transaction.message.staticAccountKeys.map((key) => key.toBase58()); const preBalances = keys.map(() => 20_000_000); const postBalances = [...preBalances]; const setDelta = (address: string, delta: bigint) => { const index = keys.indexOf(address); assert.ok(index >= 0); postBalances[index] = Number(BigInt(preBalances[index]) + delta); }; const service = 3_000_000n + 61_178n; const setupRent = 2_039_280n; const network = BigInt(this.fee); const payout = 1_000_000_000n + 2_039_280n - service - network + (this.mismatchPayout ? -1n : 0n); setDelta(this.wallet.publicKey.toBase58(), payout); const payer = keys[0]; setDelta(payer, -network - setupRent); const treasury = keys.find((key) => key !== payer && key !== this.wallet.publicKey.toBase58() && key !== this.tokenAddress && key !== wrappedSolAccount(this.wallet.publicKey.toBase58()) && ![COMPUTE_BUDGET_PROGRAM_ID, JUPITER_SWAP_PROGRAM_ID, LEGACY_TOKEN_PROGRAM_ID, ASSOCIATED_TOKEN_PROGRAM_ID, WRAPPED_SOL_MINT, '11111111111111111111111111111111'].includes(key))!; setDelta(treasury, service + network + setupRent); return { slot: 8, meta: { err: null, fee: this.fee, preBalances, postBalances }, transaction: { message: { accountKeys: keys } } }; }
}

class FakeJupiter implements JupiterRouter { builds = 0; quotes = 0; constructor(readonly route: JupiterBuild) {} async quote() { this.quotes += 1; const route = structuredClone(this.route); route.priceImpactPct = '0.01'; if (route.routePlan[0]?.swapInfo) route.routePlan[0].swapInfo.label = 'Raydium CLMM'; const { inputMint, outputMint, inAmount, outAmount, otherAmountThreshold, swapMode, slippageBps, priceImpactPct, routePlan } = route; return { inputMint, outputMint, inAmount, outAmount, otherAmountThreshold, swapMode, slippageBps, priceImpactPct, routePlan }; } async build() { this.builds += 1; const route = structuredClone(this.route); route.priceImpactPct = '0.01'; if (route.routePlan[0]?.swapInfo) route.routePlan[0].swapInfo.label = 'Raydium CLMM'; if (!route.swapInstruction.accounts.some((account) => account.pubkey === RAYDIUM_CLMM_PROGRAM_ID)) route.swapInstruction.accounts.push({ pubkey: RAYDIUM_CLMM_PROGRAM_ID, isSigner: false, isWritable: false }); return route; } validate(build: JupiterBuild, expected: { inputMint: string; amount: string; taker: string; payer: string; slippageBps: number; maxPriceImpactBps?: number; dexes?: string[] }, height: number) { new JupiterService('unused', 'test').validate(build, { ...expected, dexes: expected.dexes ?? ['Raydium CLMM'] }, height); } }
function recoverRegistry(mint: string) { return new ServerTokenRegistry([mint], [], [{ mint, symbol: 'TEST', decimals: 6, tokenProgram: LEGACY_TOKEN_PROGRAM_ID, extensions: [], status: 'supported', enabledActions: ['SWAP'], swapInputEnabled: true, swapOutputEnabled: false }]); }
function fixture() { const wallet = Keypair.generate(); const relayer = Keypair.generate(); const treasury = Keypair.generate(); const rpc = new FakeRecoverRpc(wallet); const route = buildRoute(wallet.publicKey.toBase58(), relayer.publicKey.toBase58(), rpc.tokenAddress, rpc.mint.toBase58()); route.priceImpactPct = '0.01'; const temporary = new MemoryTemporaryStore(); const durable = new MemoryDurableStore(); const registry = recoverRegistry(rpc.mint.toBase58()); const releases: Array<{ action: string; transactionId: string }> = []; const reservations = new Set<string>(); const released = new Set<string>(); const risk = { reserveTransactionExposure: async (input: { transactionId: string }) => { reservations.add(input.transactionId); }, releaseTransactionExposure: async (input: { action: string; transactionId: string }) => { reservations.delete(input.transactionId); if (released.has(input.transactionId)) return 'already_released' as const; released.add(input.transactionId); releases.push(input); return 'released' as const; } }; const jupiter = new FakeJupiter(route); const makeEngine = () => new RecoverEngine(temporary, durable, rpc as unknown as SolanaRpc, new LocalDevnetRelayerProvider(JSON.stringify([...relayer.secretKey])), new EmergencyControlService(durable), registry, jupiter, 120, { feeDestination: treasury.publicKey.toBase58(), swapFeeBps: 30, rentFeeBps: 300, slippageBps: 50, maxPriceImpactBps: 500, minimumUserPayoutLamports: 1, maximumNetworkFeeLamports: 600_000, maximumSponsoredCostLamports: 3_000_000, relayerLowBalanceThresholdLamports: 100_000, blockhashSlotsToExpiry: 300, preWalletMinimumBlockMargin: 180, attemptTtlSeconds: 86_400 }, risk); const engine = makeEngine(); return { wallet, relayer, treasury, rpc, route, temporary, durable, registry, engine, makeEngine, jupiter, risk, releases, released, reservations }; }
async function expectCode(action: () => Promise<unknown>, code: string) { await assert.rejects(action, (error: unknown) => error instanceof GaslessError && error.code === code); }
async function prepareReserved(f: ReturnType<typeof fixture>, label: string) { const quote = await f.engine.createQuote({ walletAddress: f.wallet.publicKey.toBase58(), network: 'devnet', tokenAccount: f.rpc.tokenAddress, clientRequestId: `${label}-quote`, requestId: `${label}-quote` }); const prepared = await f.engine.prepare(quote.quoteId, f.wallet.publicKey.toBase58(), `${label}-prepare`, true); await f.risk.reserveTransactionExposure({ transactionId: prepared.recover!.prepared!.transactionId }); return f.engine.activateSigningWindow(prepared, `${label}-activate`); }

test('Recover Value fee bases use exact floor rounding once', () => { const fees = calculateRecoverFees(1_000_000_101n, 2_039_280n, 30, 300); assert.deepEqual(fees, { swapFee: 3_000_000n, rentFee: 61_178n }); assert.equal(calculateRecoverMinimumPayout(1_000_000_101n, 2_039_280n, fees.swapFee, fees.rentFee, 5_000n, 1n), 998_973_203n); assert.throws(() => calculateRecoverMinimumPayout(100n, 0n, 1n, 0n, 100n, 1n)); });

test('Recover UI and API use one wallet invocation plus authenticated read-only status', () => { const ui = readFileSync('src/features/clean/components/RecoverConsole.tsx', 'utf8'); const api = readFileSync('server/index.ts', 'utf8'); assert.equal(ui.match(/wallet\.signTransaction\(/g)?.length, 1); for (const route of ['/api/recover/blockheight', '/api/recover/wallet-blockheight', '/api/recover/wallet-event', '/api/recover/abort-wallet-approval', '/api/recover/abort-wallet-gate', '/api/recover/status']) assert.match(ui + api, new RegExp(route.replaceAll('/', '\\/'))); const status = api.slice(api.indexOf("url.pathname === '/api/recover/status'"), api.indexOf("url.pathname === '/api/recover/quote'")); assert.doesNotMatch(status, /createQuote|prepare|submit|reserveTransactionExposure|signTransaction|broadcast/); });

test('Recover Approve click immediately prepares once and reaches the only wallet invocation without another review', () => { const ui = readFileSync('src/features/clean/components/RecoverConsole.tsx', 'utf8'); const preparing = ui.indexOf("state: 'preparing'"); const prepare = ui.indexOf("'/api/recover/prepare'"); const approval = ui.indexOf('wallet.signTransaction'); assert.ok(preparing >= 0 && preparing < prepare && prepare < approval); assert.match(ui, /view\.state === 'ready' \? 'APPROVE IN WALLET'/); assert.match(ui, /view\.state === 'preparing' \? 'PREPARING TRANSACTION…'/); assert.match(ui, /gasless:recover-wallet-invoked/); assert.doesNotMatch(ui, /prepared-review|freshnessSeconds|REFRESH TRANSACTION|\/api\/recover\/pre-wallet/); assert.equal(ui.match(/wallet\.signTransaction\(/g)?.length, 1); });

test('Recover executable downside requires a fresh preview and explicit new click', () => { const base = { minimumUserPayoutLamports: '4' } as RecoverQuoteDetails; assert.equal(recoverHasEconomicDownside(base, { ...base }), false); assert.equal(recoverHasEconomicDownside(base, { ...base, minimumUserPayoutLamports: '5' }), false); assert.equal(recoverHasEconomicDownside(base, { ...base, minimumUserPayoutLamports: '3' }), true); const ui = readFileSync('src/features/clean/components/RecoverConsole.tsx', 'utf8'); assert.match(ui, /economics_changed/); assert.match(ui, /Review the updated estimate, then approve again/); });

test('Recover margin supports realistic 5, 10, 15, 20, and 30 second approvals', () => { assert.equal(RECOVER_PRE_WALLET_MINIMUM_BLOCK_MARGIN, 110); for (const seconds of [5, 10, 15, 20, 30]) { const result = evaluateRecoverApprovalDelay(seconds); assert.equal(result.safe, true, `${seconds}s approval should preserve the post-sign floor`); } assert.deepEqual(evaluateRecoverApprovalDelay(30), { safe: true, remainingBlocks: 35 }); assert.equal(evaluateRecoverApprovalDelay(33).safe, false); });

test('Recover preview is temporary, read-only, and contains no executable or blockhash', async () => { const f = fixture(); const quote = await f.engine.createQuote({ walletAddress: f.wallet.publicKey.toBase58(), network: 'devnet', tokenAccount: f.rpc.tokenAddress, clientRequestId: 'preview-only', requestId: 'preview-only' }); assert.equal(quote.recover!.prepared, undefined); assert.equal(quote.recover!.route, null); assert.equal(f.durable.intents.size, 0); assert.equal(f.durable.transactions.size, 0); assert.equal(f.reservations.size, 0); const stored = JSON.stringify(await f.temporary.getQuote(quote.quoteId)); assert.doesNotMatch(stored, /blockhashWithMetadata|serializedTransaction|recentBlockhash|lastValidBlockHeight/); await new Promise((resolve) => setTimeout(resolve, 10)); assert.ok(await f.temporary.getQuote(quote.quoteId)); });

test('Recover Value accepts only absent or exact zero-balance native canonical wSOL state', () => { const wallet = Keypair.generate(); const address = wrappedSolAccount(wallet.publicKey.toBase58()); assert.deepEqual(inspectRecoverWrappedSol(wallet.publicKey.toBase58(), null).address, address); const data = Buffer.alloc(165); new PublicKey(WRAPPED_SOL_MINT).toBuffer().copy(data, 0); wallet.publicKey.toBuffer().copy(data, 32); data[108] = 1; data.writeUInt32LE(1, 109); data.writeBigUInt64LE(2_039_280n, 113); const account: RpcAccountInfo = { lamports: 2_039_280, owner: LEGACY_TOKEN_PROGRAM_ID, executable: false, rentEpoch: 0, data: [data.toString('base64'), 'base64'] }; assert.equal(inspectRecoverWrappedSol(wallet.publicKey.toBase58(), account).exists, true); const funded = structuredClone(account); const fundedData = Buffer.from(funded.data[0], 'base64'); fundedData.writeBigUInt64LE(1n, 64); funded.data[0] = fundedData.toString('base64'); assert.throws(() => inspectRecoverWrappedSol(wallet.publicKey.toBase58(), funded)); });

test('Recover Value caps total sponsor exposure including temporary account rent', async () => {
  const f = fixture(); (f.engine as unknown as { policy: { maximumSponsoredCostLamports: number } }).policy.maximumSponsoredCostLamports = 2_000_000;
  const quote = await f.engine.createQuote({ walletAddress: f.wallet.publicKey.toBase58(), network: 'devnet', tokenAccount: f.rpc.tokenAddress, clientRequestId: 'cap', requestId: 'cap' });
  await expectCode(() => f.engine.prepare(quote.quoteId, f.wallet.publicKey.toBase58(), 'cap-prepare'), 'RELAYER_POLICY_REJECTED');
});

test('Recover Value discovery requires exact whitelist, canonical account, legacy fungible state, and full nonzero balance', async () => { const f = fixture(); const good = await discoverRecoverAccounts(f.rpc as unknown as SolanaRpc, f.registry, f.wallet.publicKey.toBase58()); assert.equal(good.eligibleAccounts.length, 1); const blocked = await discoverRecoverAccounts(f.rpc as unknown as SolanaRpc, new ServerTokenRegistry([]), f.wallet.publicKey.toBase58()); assert.equal(blocked.eligibleAccounts.length, 0); const token2022 = new FakeRecoverRpc(f.wallet); token2022.getTokenAccountsByOwner = async (_owner: string, program: string) => program === TOKEN_2022_PROGRAM_ID ? [{ pubkey: token2022.tokenAddress, account: tokenAccount(f.wallet.publicKey, token2022.mint, { program: TOKEN_2022_PROGRAM_ID }) }] : []; assert.equal((await discoverRecoverAccounts(token2022 as unknown as SolanaRpc, new ServerTokenRegistry([token2022.mint.toBase58()]), f.wallet.publicKey.toBase58())).eligibleAccounts.length, 0); });

test('Jupiter boundary rejects stale, altered mint/output/amount/slippage, tips, foreign programs, and unexpected signers', () => { const f = fixture(); const service = new JupiterService('unused', 'test'); const expected = { inputMint: f.rpc.mint.toBase58(), amount: '123456789', taker: f.wallet.publicKey.toBase58(), payer: f.relayer.publicKey.toBase58(), slippageBps: 50, dexes: ['Raydium CLMM'] }; service.validate(f.route, expected, 10); const mutations: Array<(route: JupiterBuild) => void> = [(r) => { r.inputMint = Keypair.generate().publicKey.toBase58(); }, (r) => { r.outputMint = Keypair.generate().publicKey.toBase58(); }, (r) => { r.inAmount = '1'; }, (r) => { r.slippageBps = 51; }, (r) => { r.blockhashWithMetadata.lastValidBlockHeight = 10; }, (r) => { r.tipInstruction = r.swapInstruction; }, (r) => { r.swapInstruction.programId = Keypair.generate().publicKey.toBase58(); }, (r) => { r.swapInstruction.accounts.push({ pubkey: Keypair.generate().publicKey.toBase58(), isSigner: true, isWritable: false }); }]; for (const mutate of mutations) { const route = structuredClone(f.route); mutate(route); assert.throws(() => service.validate(route, expected, 10)); } });

test('Jupiter boundary enforces the configured price-impact ceiling', () => {
  const f = fixture(); const route = structuredClone(f.route); route.priceImpactPct = '0.0101';
  assert.throws(() => new JupiterService('unused', 'test').validate(route, { inputMint: f.rpc.mint.toBase58(), amount: '123456789', taker: f.wallet.publicKey.toBase58(), payer: f.relayer.publicKey.toBase58(), slippageBps: 50, maxPriceImpactBps: 100 }, 10));
});

test('Recover quote TTL and exact message hash bind the live Jupiter minimum output', async () => {
  const stale = fixture(); const staleQuote = await stale.engine.createQuote({ walletAddress: stale.wallet.publicKey.toBase58(), network: 'devnet', tokenAccount: stale.rpc.tokenAddress, clientRequestId: 'stale-output', requestId: 'stale-output' }); const stored = await stale.temporary.getQuote(staleQuote.quoteId); stored!.expiresAt = new Date(Date.now() - 1).toISOString(); stored!.intent.expiresAt = stored!.expiresAt; await stale.temporary.saveQuote(stored!, 120); await expectCode(() => stale.engine.prepare(staleQuote.quoteId, stale.wallet.publicKey.toBase58(), 'stale-output-prepare'), 'QUOTE_EXPIRED');
  const changed = fixture(); const quote = await changed.engine.createQuote({ walletAddress: changed.wallet.publicKey.toBase58(), network: 'devnet', tokenAccount: changed.rpc.tokenAddress, clientRequestId: 'changed-output', requestId: 'changed-output' }); const prepared = await changed.engine.prepare(quote.quoteId, changed.wallet.publicKey.toBase58(), 'changed-output-prepare'); const transaction = VersionedTransaction.deserialize(Buffer.from(prepared.recover!.prepared!.serializedTransaction, 'base64')); const keys = transaction.message.staticAccountKeys.map((key) => key.toBase58()); const jupiter = transaction.message.compiledInstructions.find((instruction) => keys[instruction.programIdIndex] === JUPITER_SWAP_PROGRAM_ID); assert.ok(jupiter); jupiter.data[0] ^= 1; transaction.sign([changed.wallet]); await expectCode(() => changed.engine.submit({ quoteId: quote.quoteId, walletAddress: changed.wallet.publicKey.toBase58(), signedTransaction: Buffer.from(transaction.serialize()).toString('base64'), clientRequestId: 'changed-output-submit', requestId: 'changed-output-submit' }), 'MESSAGE_MISMATCH');
});

test('atomic Recover Value message binds full amount, selected account, wallet, payer, close, route, and settlement', () => { const f = fixture(); const transaction = buildRecoverTransaction({ build: f.route, account: { address: f.rpc.tokenAddress, mint: f.rpc.mint.toBase58(), tokenProgram: LEGACY_TOKEN_PROGRAM_ID, tokenAmountRaw: '123456789', decimals: 6, recoverableLamports: '2039280', mintSupplyRaw: '1000000000', stateFingerprint: 'state', eligible: true }, walletAddress: f.wallet.publicKey.toBase58(), feePayer: f.relayer.publicKey.toBase58(), feeDestination: f.treasury.publicKey.toBase58(), settlementLamports: 3_066_178n }); const keys = transaction.message.staticAccountKeys.map((key) => key.toBase58()); assert.equal(keys[0], f.relayer.publicKey.toBase58()); assert.ok(keys.includes(f.wallet.publicKey.toBase58())); assert.ok(keys.includes(f.rpc.tokenAddress)); assert.ok(keys.includes(f.treasury.publicKey.toBase58())); const programs = transaction.message.compiledInstructions.map((instruction) => keys[instruction.programIdIndex]); assert.ok(programs.includes(JUPITER_SWAP_PROGRAM_ID)); assert.ok(programs.includes(LEGACY_TOKEN_PROGRAM_ID)); assert.ok(programs.includes('11111111111111111111111111111111')); });

test('Recover Value lifecycle rejects message mutation, submits once, closes source, and reconciles minimum economics', async () => {
  const bad = fixture(); const badQuote = await bad.engine.createQuote({ walletAddress: bad.wallet.publicKey.toBase58(), network: 'devnet', tokenAccount: bad.rpc.tokenAddress, clientRequestId: 'bad-quote', requestId: 'bad-quote' }); const badPrepared = await bad.engine.prepare(badQuote.quoteId, bad.wallet.publicKey.toBase58(), 'bad-prepare'); const changed = VersionedTransaction.deserialize(Buffer.from(badPrepared.recover!.prepared!.serializedTransaction, 'base64')); changed.message.compiledInstructions[0].data[0] ^= 1; changed.sign([bad.wallet]); await expectCode(() => bad.engine.submit({ quoteId: badQuote.quoteId, walletAddress: bad.wallet.publicKey.toBase58(), signedTransaction: Buffer.from(changed.serialize()).toString('base64'), clientRequestId: 'bad', requestId: 'bad' }), 'MESSAGE_MISMATCH'); assert.equal(bad.releases.length, 1); await expectCode(() => bad.engine.submit({ quoteId: badQuote.quoteId, walletAddress: bad.wallet.publicKey.toBase58(), signedTransaction: Buffer.from(changed.serialize()).toString('base64'), clientRequestId: 'reuse', requestId: 'reuse' }), 'QUOTE_ALREADY_USED');
  const f = fixture(); const quote = await f.engine.createQuote({ walletAddress: f.wallet.publicKey.toBase58(), network: 'devnet', tokenAccount: f.rpc.tokenAddress, clientRequestId: 'quote', requestId: 'quote' }); assert.equal(quote.recover!.swapServiceFeeLamports, '3000000'); assert.equal(quote.recover!.rentServiceFeeLamports, '61178'); const prepared = await f.engine.prepare(quote.quoteId, f.wallet.publicKey.toBase58(), 'prepare'); assert.equal(prepared.recover!.networkFeeLamports, '530000'); assert.equal(prepared.recover!.temporaryAccountRentLamports, '2039280'); assert.equal(prepared.recover!.sponsoredCostLamports, '2569280'); assert.equal(prepared.recover!.minimumUserPayoutLamports, '998448102'); const exact = VersionedTransaction.deserialize(Buffer.from(prepared.recover!.prepared!.serializedTransaction, 'base64')); exact.sign([f.wallet]); const result = await f.engine.submit({ quoteId: quote.quoteId, walletAddress: f.wallet.publicKey.toBase58(), signedTransaction: Buffer.from(exact.serialize()).toString('base64'), clientRequestId: 'good', requestId: 'good' }); assert.equal(result.reconciliation.status, 'confirmed'); assert.equal(f.releases.length, 1); assert.ok([...f.durable.events.values()].some((event) => (event as { eventType?: string }).eventType === 'recover_succeeded'));
});

test('Recover Value builds routing only for preparation, then fails closed on final simulation and payout mismatch', async () => { const altered = fixture(); const aq = await altered.engine.createQuote({ walletAddress: altered.wallet.publicKey.toBase58(), network: 'devnet', tokenAccount: altered.rpc.tokenAddress, clientRequestId: 'a', requestId: 'a' }); assert.equal(aq.recover!.route, null); assert.equal(altered.jupiter.quotes, 1); assert.equal(altered.jupiter.builds, 0); const ap = await altered.engine.prepare(aq.quoteId, altered.wallet.publicKey.toBase58(), 'ap'); assert.equal(ap.recover!.outputMint, WRAPPED_SOL_MINT); assert.equal((ap.recover!.route as JupiterBuild).outputMint, WRAPPED_SOL_MINT); assert.equal(altered.jupiter.builds, 1); const simulation = fixture(); const sq = await simulation.engine.createQuote({ walletAddress: simulation.wallet.publicKey.toBase58(), network: 'devnet', tokenAccount: simulation.rpc.tokenAddress, clientRequestId: 's', requestId: 's' }); const sp = await simulation.engine.prepare(sq.quoteId, simulation.wallet.publicKey.toBase58(), 'sp'); const signed = VersionedTransaction.deserialize(Buffer.from(sp.recover!.prepared!.serializedTransaction, 'base64')); signed.sign([simulation.wallet]); simulation.rpc.failFinal = true; await expectCode(() => simulation.engine.submit({ quoteId: sq.quoteId, walletAddress: simulation.wallet.publicKey.toBase58(), signedTransaction: Buffer.from(signed.serialize()).toString('base64'), clientRequestId: 'ss', requestId: 'ss' }), 'SIMULATION_FAILED'); assert.equal(simulation.rpc.sent, undefined); const mismatch = fixture(); const mq = await mismatch.engine.createQuote({ walletAddress: mismatch.wallet.publicKey.toBase58(), network: 'devnet', tokenAccount: mismatch.rpc.tokenAddress, clientRequestId: 'm', requestId: 'm' }); const mp = await mismatch.engine.prepare(mq.quoteId, mismatch.wallet.publicKey.toBase58(), 'mp'); const ms = VersionedTransaction.deserialize(Buffer.from(mp.recover!.prepared!.serializedTransaction, 'base64')); ms.sign([mismatch.wallet]); mismatch.rpc.mismatchPayout = true; await expectCode(() => mismatch.engine.submit({ quoteId: mq.quoteId, walletAddress: mismatch.wallet.publicKey.toBase58(), signedTransaction: Buffer.from(ms.serialize()).toString('base64'), clientRequestId: 'ms', requestId: 'ms' }), 'RECONCILIATION_FAILED'); });

test('Recover status is read-only and deterministic expiry releases exactly once', async () => {
  const f = fixture(); const quote = await f.engine.createQuote({ walletAddress: f.wallet.publicKey.toBase58(), network: 'devnet', tokenAccount: f.rpc.tokenAddress, clientRequestId: 'status', requestId: 'status' }); const prepared = await f.engine.prepare(quote.quoteId, f.wallet.publicKey.toBase58(), 'status-prepare'); const id = prepared.recover!.prepared!.transactionId;
  await f.durable.updateTransaction(id, { status: 'submitted', signature: 'status-only-signature' }); f.rpc.statusMode = 'pending';
  assert.equal((await f.engine.reconcileStatus(quote.quoteId, f.wallet.publicKey.toBase58(), 'devnet')).status, 'pending'); assert.equal(f.rpc.broadcastCalls, 0); assert.equal(f.releases.length, 0);
  f.rpc.statusMode = 'expired'; assert.equal((await f.engine.reconcileStatus(quote.quoteId, f.wallet.publicKey.toBase58(), 'devnet')).status, 'failed'); assert.equal((await f.engine.reconcileStatus(quote.quoteId, f.wallet.publicKey.toBase58(), 'devnet')).status, 'failed'); assert.equal(f.releases.length, 1); assert.equal(f.releases[0]?.action, 'CLEAN_RECOVER'); assert.equal(f.rpc.broadcastCalls, 0);
});

test('Recover cancellation releases once while Kora-signing ambiguity stays reserved until blockhash expiry', async () => {
  const cancelled = fixture(); const cq = await cancelled.engine.createQuote({ walletAddress: cancelled.wallet.publicKey.toBase58(), network: 'devnet', tokenAccount: cancelled.rpc.tokenAddress, clientRequestId: 'cancel', requestId: 'cancel' }); await cancelled.engine.prepare(cq.quoteId, cancelled.wallet.publicKey.toBase58(), 'cancel-prepare'); await cancelled.engine.abortWalletApproval(cq.quoteId, cancelled.wallet.publicKey.toBase58(), 'USER_EXPLICITLY_CANCELLED', false); await cancelled.engine.abortWalletApproval(cq.quoteId, cancelled.wallet.publicKey.toBase58(), 'USER_EXPLICITLY_CANCELLED', false); assert.equal(cancelled.releases.length, 1);
  const ambiguous = fixture(); const aq = await ambiguous.engine.createQuote({ walletAddress: ambiguous.wallet.publicKey.toBase58(), network: 'devnet', tokenAccount: ambiguous.rpc.tokenAddress, clientRequestId: 'ambiguous', requestId: 'ambiguous' }); const ap = await ambiguous.engine.prepare(aq.quoteId, ambiguous.wallet.publicKey.toBase58(), 'ambiguous-prepare'); const signed = VersionedTransaction.deserialize(Buffer.from(ap.recover!.prepared!.serializedTransaction, 'base64')); signed.sign([ambiguous.wallet]); (ambiguous.engine as unknown as { relayer: { signTransaction(): Promise<string> } }).relayer = { signTransaction: async () => { throw new Error('signing outcome unknown'); } }; await expectCode(() => ambiguous.engine.submit({ quoteId: aq.quoteId, walletAddress: ambiguous.wallet.publicKey.toBase58(), signedTransaction: Buffer.from(signed.serialize()).toString('base64'), clientRequestId: 'ambiguous-submit', requestId: 'ambiguous-submit' }), 'INTERNAL_ERROR'); assert.equal(ambiguous.releases.length, 0); ambiguous.rpc.statusMode = 'expired'; assert.equal((await ambiguous.engine.reconcileStatus(aq.quoteId, ambiguous.wallet.publicKey.toBase58(), 'devnet')).status, 'failed'); assert.equal(ambiguous.releases.length, 1);
});

test('Recover pre-wallet gate accepts a fresh preparation and terminalizes a near-expiry preparation once', async () => {
  const fresh = fixture(); const fq = await fresh.engine.createQuote({ walletAddress: fresh.wallet.publicKey.toBase58(), network: 'devnet', tokenAccount: fresh.rpc.tokenAddress, clientRequestId: 'fresh-gate', requestId: 'fresh-gate' }); await fresh.engine.prepare(fq.quoteId, fresh.wallet.publicKey.toBase58(), 'fresh-gate-prepare'); assert.equal(await fresh.engine.currentWalletGateBlockHeight(fq.quoteId, fresh.wallet.publicKey.toBase58()), 10); assert.equal(fresh.releases.length, 0);
  const stale = fixture(); const sq = await stale.engine.createQuote({ walletAddress: stale.wallet.publicKey.toBase58(), network: 'devnet', tokenAccount: stale.rpc.tokenAddress, clientRequestId: 'stale-gate', requestId: 'stale-gate' }); const sp = await stale.engine.prepare(sq.quoteId, stale.wallet.publicKey.toBase58(), 'stale-gate-prepare'); stale.rpc.blockHeight = sp.recover!.prepared!.lastValidBlockHeight - 179; await expectCode(() => stale.engine.currentWalletGateBlockHeight(sq.quoteId, stale.wallet.publicKey.toBase58()), 'QUOTE_EXPIRED'); await expectCode(() => stale.engine.currentWalletGateBlockHeight(sq.quoteId, stale.wallet.publicKey.toBase58()), 'QUOTE_ALREADY_USED'); assert.equal(stale.releases.length, 1); assert.equal((await stale.durable.getTransaction(sp.recover!.prepared!.transactionId))?.status, 'failed');
});

test('Recover never auto-builds a replacement; a new user click creates a distinct attempt', async () => {
  const f = fixture(); const first = await prepareReserved(f, 'one-click'); const firstTransaction = first.recover!.prepared!.transactionId; assert.equal(f.jupiter.quotes, 1); assert.equal(f.jupiter.builds, 1);
  f.rpc.blockHeight = first.recover!.prepared!.lastValidBlockHeight - 179;
  await expectCode(() => f.engine.currentWalletGateBlockHeight(first.quoteId, f.wallet.publicKey.toBase58()), 'QUOTE_EXPIRED');
  assert.equal(f.jupiter.builds, 1); assert.equal(f.releases.length, 1); assert.equal(f.reservations.size, 0);
  f.rpc.blockHeight = 10; f.route.blockhashWithMetadata.blockhash = [...Keypair.generate().publicKey.toBytes()]; f.route.blockhashWithMetadata.lastValidBlockHeight = 300;
  const explicit = await prepareReserved(f, 'explicit-second-click'); assert.notEqual(explicit.quoteId, first.quoteId); assert.notEqual(explicit.recover!.prepared!.transactionId, firstTransaction); assert.equal(f.jupiter.quotes, 2); assert.equal(f.jupiter.builds, 2); assert.equal(f.reservations.size, 1);
});

test('Recover terminal cleanup ignores quote TTL and remains idempotent under concurrent aborts', async () => {
  const f = fixture(); const prepared = await prepareReserved(f, 'expired-cleanup'); const id = prepared.recover!.prepared!.transactionId; prepared.expiresAt = new Date(Date.now() - 1).toISOString(); prepared.recover!.prepared!.walletSigningExpiresAt = new Date(Date.now() - 1).toISOString(); await f.temporary.saveQuote(prepared, 1); await new Promise((resolve) => setTimeout(resolve, 1_100)); assert.equal(await f.temporary.getQuote(prepared.quoteId), null);
  await Promise.all([f.engine.abortWalletGate(prepared.quoteId, f.wallet.publicKey.toBase58(), 'EXPIRED'), f.makeEngine().abortWalletGate(prepared.quoteId, f.wallet.publicKey.toBase58(), 'EXPIRED'), f.engine.abortWalletApproval(prepared.quoteId, f.wallet.publicKey.toBase58(), 'EXPIRED', false)]); assert.equal(f.releases.length, 1); assert.equal(f.reservations.size, 0); assert.equal((await f.durable.getTransaction(id))?.status, 'failed'); assert.equal([...f.durable.events.values()].filter((event) => (event as { eventType?: string }).eventType === 'recover_unsigned_terminal').length, 1);
});

test('Recover unsigned cleanup cannot mutate a signed or finalized durable record', async () => {
  const f = fixture(); const prepared = await prepareReserved(f, 'finalized-cleanup'); const id = prepared.recover!.prepared!.transactionId; await f.durable.updateTransaction(id, { status: 'reconciled', signature: 'final-signature' }); await expectCode(() => f.engine.abortWalletGate(prepared.quoteId, f.wallet.publicKey.toBase58(), 'INVALID_ABORT'), 'INVALID_REQUEST'); const record = await f.durable.getTransaction(id); assert.equal(record?.status, 'reconciled'); assert.equal(record?.signature, 'final-signature'); assert.equal(f.releases.length, 0);
});

test('Recover post-sign expiry never rebuilds, re-signs, calls Kora, or broadcasts', async () => {
  const f = fixture(); const quote = await f.engine.createQuote({ walletAddress: f.wallet.publicKey.toBase58(), network: 'devnet', tokenAccount: f.rpc.tokenAddress, clientRequestId: 'post-sign-expiry', requestId: 'post-sign-expiry' }); const prepared = await f.engine.prepare(quote.quoteId, f.wallet.publicKey.toBase58(), 'post-sign-expiry-prepare'); const transaction = VersionedTransaction.deserialize(Buffer.from(prepared.recover!.prepared!.serializedTransaction, 'base64')); transaction.sign([f.wallet]); const builds = f.jupiter.builds; f.rpc.blockHeight = prepared.recover!.prepared!.lastValidBlockHeight - 29; await expectCode(() => f.engine.submit({ quoteId: quote.quoteId, walletAddress: f.wallet.publicKey.toBase58(), signedTransaction: Buffer.from(transaction.serialize()).toString('base64'), clientRequestId: 'post-sign-expiry-submit', requestId: 'post-sign-expiry-submit' }), 'QUOTE_EXPIRED'); assert.equal(f.jupiter.builds, builds); assert.equal(f.rpc.sent, undefined); assert.equal(f.rpc.broadcastCalls, 0); assert.equal(f.releases.length, 1);
});

test('Recover API and UI contain no automatic unsigned refresh lifecycle', () => { const api = readFileSync('server/index.ts', 'utf8'); const engine = readFileSync('server/recover/engine.ts', 'utf8'); const ui = readFileSync('src/features/clean/components/RecoverConsole.tsx', 'utf8'); assert.doesNotMatch(api + engine + ui, /prepareForWallet|claimRecoverRefresh|unsignedRefreshesUsed|recover_refresh_budget|\/api\/recover\/pre-wallet/); assert.match(ui, /Transaction expired before approval\. Try again\./); });
