import assert from 'node:assert/strict';
import test from 'node:test';
import { Keypair } from '@solana/web3.js';
import { buildSwapTransaction, calculateRoutedInput, calculateSwapServiceFee, parseTokenAmount, validateSignedSwap, validateSwapProgramShape } from '../chains/solana/transactions/swap.js';
import { calculateSponsorReimbursement } from '../chains/solana/transactions/send.js';
import { deriveAssociatedTokenAddress } from '../chains/solana/send/accounts.js';
import { LEGACY_TOKEN_PROGRAM_ID } from '../chains/solana/claim/accounts.js';
import { GaslessError } from '../server/errors.js';
import { ASSOCIATED_TOKEN_PROGRAM_ID, COMPUTE_BUDGET_PROGRAM_ID, JUPITER_SWAP_PROGRAM_ID, METEORA_DLMM_DEX, METEORA_DLMM_PROGRAM_ID, PUMPSWAP_DEX, PUMPSWAP_PROGRAM_ID, RAYDIUM_CLMM_DEX, RAYDIUM_CLMM_PROGRAM_ID, JupiterService, parsePriceImpactBps, type JupiterBuild } from '../server/jupiter/service.js';
import { ServerTokenRegistry, type TokenRegistryEntry } from '../server/token-registry/service.js';

async function expectCode(action: () => Promise<unknown>, code: string) { await assert.rejects(action, (error: unknown) => error instanceof GaslessError && error.code === code); }
function entry(mint: string, input = true, output = true): TokenRegistryEntry { return { mint, symbol: 'TOK', decimals: 6, tokenProgram: LEGACY_TOKEN_PROGRAM_ID, extensions: [], status: 'supported', enabledActions: ['SWAP'], feePaymentEnabled: input, swapInputEnabled: input, swapOutputEnabled: output, usdPriceMicros: '1000000', solUsdPriceMicros: '200000000', priceUpdatedAt: new Date().toISOString() }; }
function route(wallet: string, payer: string, source: string, output: string, inputMint: string, outputMint: string, amount = '99699000'): JupiterBuild { return { inputMint, outputMint, inAmount: amount, outAmount: '50000000', otherAmountThreshold: '49750000', swapMode: 'ExactIn', slippageBps: 50, priceImpactPct: '0.0025', routePlan: [{ swapInfo: { label: RAYDIUM_CLMM_DEX, inputMint, outputMint, inAmount: amount, outAmount: '50000000' }, bps: 10_000 }], computeBudgetInstructions: [{ programId: COMPUTE_BUDGET_PROGRAM_ID, accounts: [], data: Buffer.from([3, 1, 0, 0, 0, 0, 0, 0, 0]).toString('base64') }], setupInstructions: [], swapInstruction: { programId: JUPITER_SWAP_PROGRAM_ID, accounts: [{ pubkey: wallet, isSigner: true, isWritable: false }, { pubkey: payer, isSigner: true, isWritable: true }, { pubkey: source, isSigner: false, isWritable: true }, { pubkey: output, isSigner: false, isWritable: true }, { pubkey: RAYDIUM_CLMM_PROGRAM_ID, isSigner: false, isWritable: false }], data: Buffer.from([1, 2, 3]).toString('base64') }, cleanupInstruction: null, otherInstructions: [], tipInstruction: null, addressesByLookupTableAddress: {}, blockhashWithMetadata: { blockhash: [...Keypair.generate().publicKey.toBytes()], lastValidBlockHeight: 100 } }; }

test('Swap amount parsing is exact and rejects malformed, zero, negative, and excessive precision', () => {
  assert.equal(parseTokenAmount('1.234567', 6), 1_234_567n); assert.equal(parseTokenAmount('9007199254740993', 6), 9_007_199_254_740_993_000_000n);
  for (const value of ['0', '-1', '1e2', '1.', '.1', '1.2345678']) assert.throws(() => parseTokenAmount(value, 6));
});

test('Swap service fee floors exact 30 bps and remains separate from reimbursement', () => {
  assert.equal(calculateSwapServiceFee(100_000_000n, 30), 300_000n); assert.equal(calculateSwapServiceFee(1n, 30), 0n); assert.equal(calculateSwapServiceFee(9_007_199_254_740_993n, 30), 27_021_597_764_222n);
  const reimbursement = calculateSponsorReimbursement(5_000n, 6, 200_000_000n, 1_000_000n); assert.equal(reimbursement, 1_000n); assert.equal(calculateRoutedInput(100_000_000n, 300_000n, reimbursement), 99_699_000n);
});

test('Swap registry enforces independent input and output capabilities', async () => {
  const input = Keypair.generate().publicKey.toBase58(); const output = Keypair.generate().publicKey.toBase58(); const registry = new ServerTokenRegistry([], [], [entry(input, true, false), entry(output, false, true)]);
  assert.equal((await registry.evaluate('SWAP', input)).entry?.swapInputEnabled, true); assert.equal((await registry.evaluate('SWAP', output)).entry?.swapOutputEnabled, true); assert.equal((await registry.evaluate('SWAP', Keypair.generate().publicKey.toBase58())).decision, 'unsupported');
});

test('Price impact parsing is deterministic and rejects malformed Jupiter values', () => {
  assert.equal(parsePriceImpactBps('0'), 0); assert.equal(parsePriceImpactBps('0.0100'), 100); assert.equal(parsePriceImpactBps('1.25'), 12_500); for (const value of [undefined, '-1', 'NaN', '1e-2']) assert.throws(() => parsePriceImpactBps(value));
});

test('Jupiter SWAP validation binds pair, amount, slippage, output ATA, price impact, programs, and signers', () => {
  const wallet = Keypair.generate().publicKey.toBase58(); const payer = Keypair.generate().publicKey.toBase58(); const inputMint = Keypair.generate().publicKey.toBase58(); const outputMint = Keypair.generate().publicKey.toBase58(); const source = deriveAssociatedTokenAddress(wallet, inputMint); const output = deriveAssociatedTokenAddress(wallet, outputMint); const original = route(wallet, payer, source, output, inputMint, outputMint); const expected = { inputMint, outputMint, outputAccount: output, amount: original.inAmount, taker: wallet, payer, slippageBps: 50, dexes: [RAYDIUM_CLMM_DEX], maxPriceImpactBps: 100 }; const service = new JupiterService('unused', 'test'); service.validate(original, expected, 10);
  const mutations: Array<(value: JupiterBuild) => void> = [(v) => { v.inputMint = outputMint; }, (v) => { v.outputMint = inputMint; }, (v) => { v.inAmount = '1'; }, (v) => { v.slippageBps = 100; }, (v) => { v.priceImpactPct = '0.0101'; }, (v) => { v.otherAmountThreshold = '50000001'; }, (v) => { v.otherInstructions = [v.swapInstruction]; }, (v) => { v.swapInstruction.programId = ASSOCIATED_TOKEN_PROGRAM_ID; }, (v) => { v.swapInstruction.accounts.push({ pubkey: Keypair.generate().publicKey.toBase58(), isSigner: true, isWritable: true }); }, (v) => { v.routePlan[0]!.swapInfo!.label = 'Flux'; }, (v) => { v.swapInstruction.accounts = v.swapInstruction.accounts.filter((account) => account.pubkey !== RAYDIUM_CLMM_PROGRAM_ID); }, (v) => { v.swapInstruction.accounts = v.swapInstruction.accounts.filter((account) => account.pubkey !== output); }];
  for (const mutate of mutations) { const changed = structuredClone(original); mutate(changed); assert.throws(() => service.validate(changed, expected, 10)); }
});

test('Jupiter build always sends the exact Raydium CLMM dex restriction', async () => {
  let requested = ''; const response = route(Keypair.generate().publicKey.toBase58(), Keypair.generate().publicKey.toBase58(), Keypair.generate().publicKey.toBase58(), Keypair.generate().publicKey.toBase58(), Keypair.generate().publicKey.toBase58(), Keypair.generate().publicKey.toBase58(), '1');
  const service = new JupiterService('https://example.test', 'key', (async (url: string | URL | Request) => { requested = String(url); return new Response(JSON.stringify(response), { status: 200, headers: { 'content-type': 'application/json' } }); }) as typeof fetch);
  const destinationTokenAccount = Keypair.generate().publicKey.toBase58();
  await service.build({ inputMint: response.inputMint, outputMint: response.outputMint, amount: '1', taker: Keypair.generate().publicKey.toBase58(), payer: Keypair.generate().publicKey.toBase58(), destinationTokenAccount, slippageBps: 50, dexes: [RAYDIUM_CLMM_DEX], blockhashSlotsToExpiry: 150 });
  assert.equal(new URL(requested).searchParams.get('dexes'), RAYDIUM_CLMM_DEX);
  assert.equal(new URL(requested).searchParams.get('maxAccounts'), '24');
  assert.equal(new URL(requested).searchParams.get('destinationTokenAccount'), destinationTokenAccount);
  assert.equal(new URL(requested).searchParams.get('blockhashSlotsToExpiry'), '150');
  await assert.rejects(() => service.build({ inputMint: response.inputMint, outputMint: response.outputMint, amount: '1', taker: Keypair.generate().publicKey.toBase58(), payer: Keypair.generate().publicKey.toBase58(), slippageBps: 50, blockhashSlotsToExpiry: 151 }), (error: unknown) => error instanceof GaslessError && error.code === 'CONFIGURATION_ERROR');
});

test('Jupiter permits only unique canonical input/output ATA setup and Swap includes only a missing output setup', () => {
  const wallet = Keypair.generate().publicKey.toBase58(); const payer = Keypair.generate().publicKey.toBase58(); const inputMint = Keypair.generate().publicKey.toBase58(); const outputMint = Keypair.generate().publicKey.toBase58(); const source = deriveAssociatedTokenAddress(wallet, inputMint); const output = deriveAssociatedTokenAddress(wallet, outputMint); const build = route(wallet, payer, source, output, inputMint, outputMint); const setup = (account: string, mint: string) => ({ programId: ASSOCIATED_TOKEN_PROGRAM_ID, accounts: [{ pubkey: payer, isSigner: true, isWritable: true }, { pubkey: account, isSigner: false, isWritable: true }, { pubkey: wallet, isSigner: false, isWritable: false }, { pubkey: mint, isSigner: false, isWritable: false }, { pubkey: '11111111111111111111111111111111', isSigner: false, isWritable: false }, { pubkey: LEGACY_TOKEN_PROGRAM_ID, isSigner: false, isWritable: false }], data: Buffer.from([1]).toString('base64') });
  build.setupInstructions = [setup(source, inputMint), setup(output, outputMint)]; const expected = { inputMint, outputMint, outputAccount: output, amount: build.inAmount, taker: wallet, payer, slippageBps: 50, dexes: [RAYDIUM_CLMM_DEX], maxPriceImpactBps: 100 }; new JupiterService('unused', 'test').validate(build, expected, 10);
  for (const unsafe of [[...build.setupInstructions, setup(output, outputMint)], [setup(Keypair.generate().publicKey.toBase58(), outputMint)]]) { const changed = structuredClone(build); changed.setupInstructions = unsafe; assert.throws(() => new JupiterService('unused', 'test').validate(changed, expected, 10)); }
  const transaction = buildSwapTransaction({ swap: { schemaVersion: 'swap-v1', inputToken: { ...entry(inputMint), balanceRaw: '100000000', sourceAccount: source, swapInputEnabled: true, swapOutputEnabled: false }, outputToken: { ...entry(outputMint, false, true), swapInputEnabled: false, swapOutputEnabled: true }, outputAccount: output, outputAtaExists: false, totalInputRaw: '100000000', routedInputRaw: build.inAmount, expectedOutputRaw: build.outAmount, minimumOutputRaw: build.otherAmountThreshold, serviceFeeBps: 30, serviceFeeRaw: '1', sponsorReimbursementRaw: '1', slippageBps: 50, priceImpactBps: 25, routeLabel: RAYDIUM_CLMM_DEX, routeFingerprint: 'x', reimbursementDestination: source, serviceFeeDestination: source, status: 'created', route: build }, build, walletAddress: wallet, feePayer: payer });
  const programs = transaction.message.compiledInstructions.map((instruction) => transaction.message.staticAccountKeys[instruction.programIdIndex]?.toBase58()); assert.equal(programs.filter((program) => program === ASSOCIATED_TOKEN_PROGRAM_ID).length, 1);
});

test('Jupiter binds each approved V1 family label to its exact program and rejects multi-family routes', () => {
  const wallet = Keypair.generate().publicKey.toBase58(); const payer = Keypair.generate().publicKey.toBase58(); const inputMint = Keypair.generate().publicKey.toBase58(); const outputMint = Keypair.generate().publicKey.toBase58(); const source = deriveAssociatedTokenAddress(wallet, inputMint); const output = deriveAssociatedTokenAddress(wallet, outputMint); const service = new JupiterService('unused', 'test');
  for (const [family, program] of [[RAYDIUM_CLMM_DEX, RAYDIUM_CLMM_PROGRAM_ID], [METEORA_DLMM_DEX, METEORA_DLMM_PROGRAM_ID], [PUMPSWAP_DEX, PUMPSWAP_PROGRAM_ID]] as const) {
    const build = route(wallet, payer, source, output, inputMint, outputMint); build.routePlan[0]!.swapInfo!.label = family; build.swapInstruction.accounts[4]!.pubkey = program;
    const expected = { inputMint, outputMint, outputAccount: output, amount: build.inAmount, taker: wallet, payer, slippageBps: 50, dexes: [family], maxPriceImpactBps: 100 };
    service.validate(build, expected, 10);
    const mismatch = structuredClone(build); mismatch.swapInstruction.accounts[4]!.pubkey = program === RAYDIUM_CLMM_PROGRAM_ID ? METEORA_DLMM_PROGRAM_ID : RAYDIUM_CLMM_PROGRAM_ID; assert.throws(() => service.validate(mismatch, expected, 10));
    const multi = structuredClone(build); multi.routePlan.push(structuredClone(multi.routePlan[0]!)); assert.throws(() => service.validate(multi, expected, 10));
  }
});

test('missing Raydium-only route fails closed without broadening the request', async () => {
  let requested = '';
  const service = new JupiterService('https://example.test', 'key', (async (url: string | URL | Request) => { requested = String(url); return new Response('{}', { status: 400 }); }) as typeof fetch);
  await assert.rejects(
    () => service.build({ inputMint: Keypair.generate().publicKey.toBase58(), outputMint: Keypair.generate().publicKey.toBase58(), amount: '1', taker: Keypair.generate().publicKey.toBase58(), payer: Keypair.generate().publicKey.toBase58(), slippageBps: 50, dexes: [RAYDIUM_CLMM_DEX] }),
    (error: unknown) => error instanceof GaslessError && error.message === 'No safe swap route is available for this pair right now.',
  );
  assert.equal(new URL(requested).searchParams.get('dexes'), RAYDIUM_CLMM_DEX);
});

test('pre-sign simulation accepts only Raydium CLMM and rejects unknown or wrongly nested CPI programs', () => {
  const wallet = Keypair.generate(); const payer = Keypair.generate(); const inputMint = Keypair.generate().publicKey.toBase58(); const outputMint = Keypair.generate().publicKey.toBase58(); const source = deriveAssociatedTokenAddress(wallet.publicKey.toBase58(), inputMint); const output = deriveAssociatedTokenAddress(wallet.publicKey.toBase58(), outputMint); const build = route(wallet.publicKey.toBase58(), payer.publicKey.toBase58(), source, output, inputMint, outputMint); const swap = { schemaVersion: 'swap-v1' as const, inputToken: { ...entry(inputMint), balanceRaw: '100000000', sourceAccount: source, swapInputEnabled: true, swapOutputEnabled: false }, outputToken: { ...entry(outputMint, false, true), swapInputEnabled: false, swapOutputEnabled: true }, outputAccount: output, outputAtaExists: true, totalInputRaw: '100000000', routedInputRaw: '99699000', expectedOutputRaw: '50000000', minimumOutputRaw: '49750000', serviceFeeBps: 30, serviceFeeRaw: '300000', sponsorReimbursementRaw: '1000', outputAtaRentLamports: '0', networkFeeLamports: '5000', sponsoredCostLamports: '5000', slippageBps: 50, priceImpactBps: 25, routeLabel: RAYDIUM_CLMM_DEX, routeFingerprint: 'x', reimbursementDestination: deriveAssociatedTokenAddress(Keypair.generate().publicKey.toBase58(), inputMint), serviceFeeDestination: deriveAssociatedTokenAddress(Keypair.generate().publicKey.toBase58(), inputMint), status: 'created' as const, route: build }; const transaction = buildSwapTransaction({ swap, build, walletAddress: wallet.publicKey.toBase58(), feePayer: payer.publicKey.toBase58() }); const jupiterIndex = transaction.message.compiledInstructions.findIndex((instruction) => transaction.message.staticAccountKeys[instruction.programIdIndex]?.toBase58() === JUPITER_SWAP_PROGRAM_ID); const valid = [{ index: jupiterIndex, instructions: [{ programId: RAYDIUM_CLMM_PROGRAM_ID, stackHeight: 2 }, { programId: LEGACY_TOKEN_PROGRAM_ID, stackHeight: 3 }] }];
  validateSwapProgramShape(transaction, build, valid, true, payer.publicKey.toBase58(), wallet.publicKey.toBase58());
  for (const programId of ['FLUXubRmkEiH8U1c3EELFxQ4Lk4TqGRQcE9m3h7gV2V', 'LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo', Keypair.generate().publicKey.toBase58()]) assert.throws(() => validateSwapProgramShape(transaction, build, [{ index: jupiterIndex, instructions: [{ programId, stackHeight: 2 }] }], true, payer.publicKey.toBase58(), wallet.publicKey.toBase58()));
  assert.throws(() => validateSwapProgramShape(transaction, build, [{ index: jupiterIndex, instructions: [{ programId: '11111111111111111111111111111111', stackHeight: 2 }, { programId: RAYDIUM_CLMM_PROGRAM_ID, stackHeight: 2 }] }], true, payer.publicKey.toBase58(), wallet.publicKey.toBase58()));
  assert.throws(() => validateSwapProgramShape(transaction, build, [{ index: jupiterIndex, instructions: [{ programId: RAYDIUM_CLMM_PROGRAM_ID, stackHeight: 3 }] }], true, payer.publicKey.toBase58(), wallet.publicKey.toBase58()));
  assert.throws(() => validateSwapProgramShape(transaction, build, null, true, payer.publicKey.toBase58(), wallet.publicKey.toBase58()));
});

test('Signed SWAP validation rejects a modified exact message and missing user signature', async () => {
  const wallet = Keypair.generate(); const payer = Keypair.generate(); const inputMint = Keypair.generate().publicKey.toBase58(); const outputMint = Keypair.generate().publicKey.toBase58(); const source = deriveAssociatedTokenAddress(wallet.publicKey.toBase58(), inputMint); const output = deriveAssociatedTokenAddress(wallet.publicKey.toBase58(), outputMint); const build = route(wallet.publicKey.toBase58(), payer.publicKey.toBase58(), source, output, inputMint, outputMint); const { buildSwapTransaction } = await import('../chains/solana/transactions/swap.js'); const swap = { schemaVersion: 'swap-v1' as const, inputToken: { ...entry(inputMint), balanceRaw: '100000000', sourceAccount: source, swapInputEnabled: true, swapOutputEnabled: false }, outputToken: { ...entry(outputMint, false, true), swapInputEnabled: false, swapOutputEnabled: true }, outputAccount: output, outputAtaExists: true, totalInputRaw: '100000000', routedInputRaw: '99699000', expectedOutputRaw: '50000000', minimumOutputRaw: '49750000', serviceFeeBps: 30, serviceFeeRaw: '300000', sponsorReimbursementRaw: '1000', outputAtaRentLamports: '0', networkFeeLamports: '5000', sponsoredCostLamports: '5000', slippageBps: 50, priceImpactBps: 25, routeLabel: 'Test', routeFingerprint: 'x', reimbursementDestination: deriveAssociatedTokenAddress(Keypair.generate().publicKey.toBase58(), inputMint), serviceFeeDestination: deriveAssociatedTokenAddress(Keypair.generate().publicKey.toBase58(), inputMint), status: 'created' as const, route: build }; const transaction = buildSwapTransaction({ swap, build, walletAddress: wallet.publicKey.toBase58(), feePayer: payer.publicKey.toBase58() }); const hash = (await import('../chains/solana/transactions/recover.js')).versionedMessageHash(transaction); const prepared = { transactionId: crypto.randomUUID(), quoteId: crypto.randomUUID(), intentId: crypto.randomUUID(), walletAddress: wallet.publicKey.toBase58(), network: 'devnet' as const, serializedTransaction: Buffer.from(transaction.serialize()).toString('base64'), preparedMessageHash: hash, expectedFeePayer: payer.publicKey.toBase58(), expectedSigners: [payer.publicKey.toBase58(), wallet.publicKey.toBase58()], allowedProgramIds: [], recentBlockhash: transaction.message.recentBlockhash, lastValidBlockHeight: 100, walletSigningExpiresAt: new Date(Date.now() + 30_000).toISOString(), simulation: { success: true, provider: 'fake', simulatedAt: new Date().toISOString() } }; const rpc = { getBlockHeight: async () => 10 };
  await expectCode(() => validateSignedSwap(prepared.serializedTransaction, prepared, rpc as never), 'USER_SIGNATURE_INVALID'); transaction.sign([wallet]); const signed = Buffer.from(transaction.serialize()).toString('base64'); await validateSignedSwap(signed, prepared, rpc as never); await expectCode(() => validateSignedSwap(signed, { ...prepared, walletSigningExpiresAt: new Date(Date.now() - 1).toISOString() }, rpc as never), 'QUOTE_EXPIRED'); transaction.message.compiledInstructions[0].data[0] ^= 1; transaction.sign([wallet]); await expectCode(() => validateSignedSwap(Buffer.from(transaction.serialize()).toString('base64'), prepared, rpc as never), 'MESSAGE_MISMATCH');
});
