import { PublicKey, VersionedTransaction } from '@solana/web3.js';
import { discoverSwapTokens, validateSwapOutputAccount } from '../../chains/solana/swap/accounts.js';
import { calculateRoutedInput, calculateSwapServiceFee, estimateSwapNetworkFee, parseTokenAmount, prepareSwapTransaction, validateSignedSwap } from '../../chains/solana/transactions/swap.js';
import { calculateSponsorReimbursement } from '../../chains/solana/transactions/send.js';
import { versionedMessageHash, versionedSignerSignatureIsValid } from '../../chains/solana/transactions/clean.js';
import { deriveAssociatedTokenAddress, inspectSendTokenAccount, validateDestinationAccount } from '../../chains/solana/send/accounts.js';
import type { DurableTransactionRecord, ReconciliationResult, SolanaNetwork, SwapQuoteDetails, TransactionIntent, TransactionQuote } from '../../shared/transactions/types.js';
import type { EmergencyControlService } from '../controls/service.js';
import { GaslessError, asGaslessError } from '../errors.js';
import { APPROVED_DEX_FAMILIES, RAYDIUM_CLMM_DEX, type ApprovedDexFamily, type JupiterBuild, type JupiterRouter, parsePriceImpactBps, routeDexFamily, routeFingerprint } from '../jupiter/service.js';
import { log } from '../observability/logger.js';
import { koraFailure, type KoraCallFailure, type RelayerProvider } from '../relayer/provider.js';
import type { OperationalRiskService } from '../risk/operational.js';
import type { SolanaRpc } from '../solana/rpc.js';
import type { DurableStore } from '../storage/durable.js';
import type { TemporaryStore } from '../storage/temporary.js';
import type { TokenRegistry, TokenRegistryEntry } from '../token-registry/service.js';
import { WRAPPED_SOL_MINT, type PriceProvider } from '../pricing/service.js';
import { SWAP_MINIMUM_BLOCK_HEIGHT_MARGIN, signingDeadlineHasMargin, swapSigningDeadline } from '../../chains/solana/swap/validity.js';

interface SwapPolicy { reimbursementWallet?: string; serviceFeeWallet?: string; serviceFeeBps: number; defaultSlippageBps: number; maximumSlippageBps: number; maximumPriceImpactBps: number; priceMaxAgeSeconds: number; maximumSponsoredCostLamports: number; relayerLowBalanceThresholdLamports: number }
const ALLOWED_SLIPPAGE_BPS = new Set([30, 50, 100]);
const MAX_STABILIZATION_ATTEMPTS = 6;

export function canReleaseAfterKoraFailure(
  failure: KoraCallFailure | undefined,
  state: { payerSigned: boolean; signature?: string; broadcastAttempted: boolean },
) {
  return Boolean(
    failure?.deterministicPreSignRejection
    && !failure.payerSignatureReturned
    && !state.payerSigned
    && !state.signature
    && !state.broadcastAttempted,
  );
}

export class SwapEngine {
  constructor(private readonly temporary: TemporaryStore, private readonly durable: DurableStore, private readonly rpc: SolanaRpc, private readonly relayer: RelayerProvider, private readonly controls: EmergencyControlService, private readonly registry: TokenRegistry, private readonly jupiter: JupiterRouter, private readonly quoteTtlSeconds: number, private readonly policy: SwapPolicy, private readonly prices?: PriceProvider, private readonly risk?: Pick<OperationalRiskService, 'releaseQuoteExposure'>) {}

  async discover(walletAddress: string, network: SolanaNetwork = 'devnet') { return { ...await discoverSwapTokens(this.rpc, walletAddress, await this.activeEntries()), network }; }
  async listTokens() { return (await this.activeEntries()).map(({ mint, symbol, decimals, swapInputEnabled, swapOutputEnabled }) => ({ mint, symbol, decimals, swapInputEnabled, swapOutputEnabled })); }

  async createQuote(input: { walletAddress: string; network: SolanaNetwork; inputMint: string; outputMint: string; amount: string; slippageBps?: number; clientRequestId: string; requestId: string; authorityVersion?: number }) {
    if (!await this.temporary.consumeRateLimit(`swap-quote:${input.walletAddress}`, 10, 60)) throw new GaslessError('RATE_LIMITED', 'swap_quote', 'Too many swap requests. Wait a minute and try again.', true);
    if (!await this.temporary.acquireReplayLock(`swap-request:${input.walletAddress}:${input.clientRequestId}`, input.requestId, this.quoteTtlSeconds)) throw new GaslessError('REPLAY_DETECTED', 'swap_quote', 'This swap request was already received.');
    let wallet: string; try { wallet = new PublicKey(input.walletAddress).toBase58(); new PublicKey(input.inputMint); new PublicKey(input.outputMint); } catch { throw new GaslessError('INVALID_REQUEST', 'swap_pair', 'Choose a valid supported token pair.'); }
    const inputEntry = await this.priced(await this.requireEntry(input.inputMint, 'input')); const outputEntry = await this.requireEntry(input.outputMint, 'output'); this.assertPolicy(inputEntry, outputEntry); this.assertDestinations(wallet);
    if (input.inputMint === input.outputMint) throw new GaslessError('INVALID_REQUEST', 'swap_pair', 'Choose two different tokens to swap.');
    const slippageBps = input.slippageBps ?? this.policy.defaultSlippageBps;
    if (!ALLOWED_SLIPPAGE_BPS.has(slippageBps) || slippageBps > this.policy.maximumSlippageBps) throw new GaslessError('INVALID_REQUEST', 'swap_slippage', 'Choose one of the available slippage settings.');
    const sourceAddress = deriveAssociatedTokenAddress(wallet, inputEntry.mint, inputEntry.tokenProgram); const source = inspectSendTokenAccount(sourceAddress, await this.rpc.getAccountInfo(sourceAddress), wallet, inputEntry);
    if (!source) throw new GaslessError('TOKEN_UNSUPPORTED', 'swap_source', 'This input token account is not eligible for GASLESS Swap.');
    const totalInput = parseTokenAmount(input.amount, inputEntry.decimals); if (totalInput > BigInt(source.balanceRaw)) throw new GaslessError('INSUFFICIENT_BALANCE', 'swap_amount', `You do not have enough ${inputEntry.symbol} for this swap.`);
    const outputAccount = deriveAssociatedTokenAddress(wallet, outputEntry.mint, outputEntry.tokenProgram); let outputAtaExists: boolean;
    try { outputAtaExists = validateSwapOutputAccount(await this.rpc.getAccountInfo(outputAccount), wallet, outputEntry).exists; } catch { throw new GaslessError('TOKEN_UNSUPPORTED', 'swap_output_account', 'We could not safely prepare your receiving token account.'); }
    const { reimbursementDestination, serviceFeeDestination } = await this.requireSettlementAccounts(inputEntry);
    const ataRent = outputAtaExists ? 0n : BigInt(await this.rpc.getMinimumBalanceForRentExemption(165)); const serviceFee = calculateSwapServiceFee(totalInput, this.policy.serviceFeeBps); const feePayer = await this.relayer.getFeePayerPublicKey();
    const approvedDexFamilies = this.approvedDexFamilies(inputEntry, outputEntry); let dexFamily: ApprovedDexFamily | undefined;
    let reimbursement = calculateSponsorReimbursement(ataRent + 10_000n, inputEntry.decimals, BigInt(inputEntry.solUsdPriceMicros!), BigInt(inputEntry.usdPriceMicros!), inputEntry.reimbursementBufferBps ?? 0); let build!: JupiterBuild; let networkFee = 0n; let swap!: SwapQuoteDetails;
    for (let attempt = 0; attempt < MAX_STABILIZATION_ATTEMPTS; attempt += 1) {
      const routedInput = calculateRoutedInput(totalInput, serviceFee, reimbursement);
      const selected = await this.buildRoute({ inputMint: inputEntry.mint, outputMint: outputEntry.mint, amount: routedInput.toString(), taker: wallet, payer: feePayer, outputAccount, slippageBps }, dexFamily ? [dexFamily] : approvedDexFamilies);
      build = selected.build; dexFamily = selected.family;
      if (outputAtaExists) { try { if (!validateSwapOutputAccount(await this.rpc.getAccountInfo(outputAccount), wallet, outputEntry).exists) throw new Error(); } catch { throw new GaslessError('JUPITER_ROUTE_REJECTED', 'swap_output_account', 'The existing receiving token account changed during quote construction.'); } build = { ...build, setupInstructions: [] }; }
      else if (build.setupInstructions.length !== 1) throw new GaslessError('JUPITER_ROUTE_REJECTED', 'swap_output_account', 'Jupiter returned unexpected receiving-account setup.');
      swap = this.details(source, inputEntry, outputEntry, outputAccount, outputAtaExists, totalInput, routedInput, serviceFee, reimbursement, ataRent, slippageBps, build, reimbursementDestination, serviceFeeDestination);
      networkFee = await estimateSwapNetworkFee({ swap, build, walletAddress: wallet, feePayer, rpc: this.rpc });
      const sponsored = networkFee + ataRent; if (sponsored > BigInt(this.policy.maximumSponsoredCostLamports)) throw new GaslessError('RELAYER_POLICY_REJECTED', 'swap_sponsor_cost', 'This swap exceeds the GASLESS sponsorship limit.');
      const exact = calculateSponsorReimbursement(sponsored, inputEntry.decimals, BigInt(inputEntry.solUsdPriceMicros!), BigInt(inputEntry.usdPriceMicros!), inputEntry.reimbursementBufferBps ?? 0);
      if (exact === reimbursement) break; reimbursement = exact;
      if (attempt === MAX_STABILIZATION_ATTEMPTS - 1) throw new GaslessError('JUPITER_UNAVAILABLE', 'swap_economics', 'Swap costs did not stabilize. Request a fresh quote.', true);
    }
    Object.assign(swap, { sponsoredCostLamports: (networkFee + ataRent).toString(), networkFeeLamports: networkFee.toString() });
    const now = Date.now(); const intent: TransactionIntent = { intentId: crypto.randomUUID(), walletAddress: wallet, actionType: 'SWAP', network: input.network, requestId: input.requestId, clientRequestId: input.clientRequestId, createdAt: new Date(now).toISOString(), expiresAt: new Date(now + this.quoteTtlSeconds * 1000).toISOString(), metadata: { schemaVersion: 'swap-v1', inputMint: inputEntry.mint, outputMint: outputEntry.mint } };
    const quote: TransactionQuote = { quoteId: crypto.randomUUID(), intent, status: 'created', createdAt: intent.createdAt, expiresAt: intent.expiresAt, swap: { ...swap, route: build } };
    await this.temporary.saveQuote(quote, this.quoteTtlSeconds); await this.durable.createIntent(intent, quote.quoteId); if (!await this.temporary.setAuthoritativeSwapQuote(this.authorityKey(input.network, wallet), quote.quoteId, input.authorityVersion ?? now, this.quoteTtlSeconds)) throw this.refreshRequired(); log('info', 'swap_quote_created', { requestId: input.requestId, quoteId: quote.quoteId, walletAddress: wallet, inputMint: inputEntry.mint, outputMint: outputEntry.mint, routedInputRaw: swap.routedInputRaw }); return quote;
  }

  async prepare(quoteId: string, walletAddress: string, requestId: string) {
    const quote = await this.requireQuote(quoteId, walletAddress); const swap = quote.swap!;
    if (swap.prepared) { if (!signingDeadlineHasMargin(swap.prepared.walletSigningExpiresAt)) throw this.refreshRequired(); return quote; }
    if (!swapSigningDeadline(quote.expiresAt)) throw this.refreshRequired();
    await this.controls.assertExecutionAllowed('SWAP', quote.intent.network); await this.recheck(swap, walletAddress);
    const savedBuild = swap.route as JupiterBuild; const feePayer = await this.relayer.getFeePayerPublicKey(); if (routeFingerprint(savedBuild) !== swap.routeFingerprint) throw new GaslessError('JUPITER_ROUTE_REJECTED', 'jupiter_validation', 'The saved route changed after quoting.');
    const latest = await this.rpc.getLatestBlockhash(); const build: JupiterBuild = { ...savedBuild, blockhashWithMetadata: { blockhash: [...new PublicKey(latest.blockhash).toBytes()], lastValidBlockHeight: latest.lastValidBlockHeight } };
    this.jupiter.validate(build, { inputMint: swap.inputToken.mint, outputMint: swap.outputToken.mint, outputAccount: swap.outputAccount, amount: swap.routedInputRaw, taker: walletAddress, payer: feePayer, slippageBps: swap.slippageBps, dexes: [routeDexFamily(build)], maxPriceImpactBps: this.policy.maximumPriceImpactBps }, await this.rpc.getBlockHeight());
    const prepared = await prepareSwapTransaction({ quote, swap, build, feePayer, rpc: this.rpc }); const currentBlockHeight = await this.rpc.getBlockHeight(); const walletSigningExpiresAt = swapSigningDeadline(quote.expiresAt);
    if (!walletSigningExpiresAt || prepared.lastValidBlockHeight - currentBlockHeight < SWAP_MINIMUM_BLOCK_HEIGHT_MARGIN) throw this.refreshRequired();
    prepared.walletSigningExpiresAt = walletSigningExpiresAt; Object.assign(swap, { prepared, expectedRelayer: feePayer, status: 'awaiting_user_signature' }); quote.status = 'awaiting_user_signature';
    const now = new Date().toISOString(); const record: DurableTransactionRecord = { id: prepared.transactionId, intentId: quote.intent.intentId, quoteId, walletAddress, actionType: 'SWAP', network: quote.intent.network, status: quote.status, preparedMessageHash: prepared.preparedMessageHash, inputMint: swap.inputToken.mint, outputMint: swap.outputToken.mint, outputTokenDecimals: swap.outputToken.decimals, mint: swap.inputToken.mint, tokenAccount: swap.inputToken.sourceAccount, tokenAmountRaw: swap.totalInputRaw, tokenDecimals: swap.inputToken.decimals, routedInputRaw: swap.routedInputRaw, expectedOutputRaw: swap.expectedOutputRaw, minimumOutputRaw: swap.minimumOutputRaw, serviceFeeRaw: swap.serviceFeeRaw, sponsorReimbursementRaw: swap.sponsorReimbursementRaw, sponsoredCostLamports: swap.sponsoredCostLamports, networkFeeLamports: swap.networkFeeLamports, outputAccount: swap.outputAccount, outputAtaCreated: !swap.outputAtaExists, outputAtaRentLamports: swap.outputAtaRentLamports, slippageBps: swap.slippageBps, priceImpactBps: swap.priceImpactBps, routeFingerprint: swap.routeFingerprint, reimbursementDestination: swap.reimbursementDestination, serviceFeeDestination: swap.serviceFeeDestination, relayerAddress: feePayer, createdAt: now, updatedAt: now };
    await this.durable.createTransaction(record); await this.durable.updateIntentStatus(quote.intent.intentId, quote.status); await this.durable.appendEvent(prepared.transactionId, 'swap_prepared', 'prepared', { simulation: 'passed' }, `${prepared.transactionId}:prepared`); await this.persistQuote(quote); log('info', 'swap_prepared', { requestId, quoteId, transactionId: prepared.transactionId }); return quote;
  }

  async submit(input: { quoteId: string; walletAddress: string; signedTransaction: string; clientRequestId: string; requestId: string }) {
    const quote = await this.requireQuote(input.quoteId, input.walletAddress, true); const swap = quote.swap!; if (!swap.prepared) throw new GaslessError('INVALID_REQUEST', 'swap_submit', 'Prepare this swap before submitting it.');
    if (swap.status === 'reconciled' && swap.signature && swap.reconciliation) { await this.releaseSuccessfulExposure(quote); return { transactionId: swap.prepared.transactionId, signature: swap.signature, reconciliation: swap.reconciliation, alreadyCompleted: true }; }
    if (swap.status === 'submitted' && swap.signature) return this.resumeSubmitted(quote); await this.controls.assertExecutionAllowed('SWAP', quote.intent.network); if (!await this.temporary.consumeRateLimit(`swap-submit:${input.walletAddress}`, 5, 60)) throw new GaslessError('RATE_LIMITED', 'swap_submit', 'Too many swap attempts. Wait a minute and try again.', true);
    const keys = [`swap-submission:${input.quoteId}`, `message:${swap.prepared.preparedMessageHash}`, `swap-submit-request:${input.walletAddress}:${input.clientRequestId}`]; const acquired: string[] = []; let crossed = false; let payerSigned = false; let broadcastAttempted = false; let signature: string | undefined;
    try {
      for (const key of keys) { if (!await this.temporary.acquireReplayLock(key, input.requestId, 86_400)) throw new GaslessError('REPLAY_DETECTED', 'replay', 'This swap was already submitted.'); acquired.push(key); }
      const validated = await validateSignedSwap(input.signedTransaction, swap.prepared, this.rpc);
      if (validated.messageHash !== swap.prepared.preparedMessageHash) { const finalMessageKey = `message:${validated.messageHash}`; if (!await this.temporary.acquireReplayLock(finalMessageKey, input.requestId, 86_400)) throw new GaslessError('REPLAY_DETECTED', 'replay', 'This swap was already submitted.'); acquired.push(finalMessageKey); }
      await this.recheck(swap, input.walletAddress); await this.controls.assertExecutionAllowed('SWAP', quote.intent.network); const transaction = VersionedTransaction.deserialize(Buffer.from(validated.serializedTransaction, 'base64')); const fee = await this.rpc.getFeeForMessage(Buffer.from(transaction.message.serialize()).toString('base64'));
      if (fee === null || String(fee) !== swap.networkFeeLamports || BigInt(swap.sponsoredCostLamports!) > BigInt(this.policy.maximumSponsoredCostLamports)) throw new GaslessError('RELAYER_POLICY_REJECTED', 'relayer_boundary', 'The sponsored swap cost no longer matches the preview.');
      if (await this.rpc.getBalance(swap.prepared.expectedFeePayer) < Number(BigInt(swap.sponsoredCostLamports!)) + this.policy.relayerLowBalanceThresholdLamports) throw new GaslessError('RELAYER_INSUFFICIENT_FUNDS', 'relayer_boundary', 'GASLESS Swap is temporarily unavailable. Your tokens have not moved.');
      crossed = true; swap.status = 'relaying'; quote.status = 'relaying'; await this.persistQuote(quote); await this.durable.updateTransaction(swap.prepared.transactionId, { status: 'relaying', updatedAt: new Date().toISOString() }); const fullySigned = await this.relayer.signTransaction(validated.serializedTransaction); payerSigned = true;
      const fullySignedTransaction = VersionedTransaction.deserialize(Buffer.from(fullySigned, 'base64')); if (versionedMessageHash(fullySignedTransaction) !== validated.messageHash || fullySignedTransaction.message.recentBlockhash !== swap.prepared.recentBlockhash) throw new GaslessError('MESSAGE_MISMATCH', 'relayer_boundary', 'The signed swap changed after approval. Nothing was submitted.');
      if (!versionedSignerSignatureIsValid(fullySignedTransaction, 0, swap.prepared.expectedFeePayer)) throw new GaslessError('RELAYER_POLICY_REJECTED', 'relayer_boundary', 'The swap payer signature is invalid. Nothing was submitted.');
      const simulation = await this.rpc.simulateTransaction(fullySigned, true); if (simulation.err !== null) throw new GaslessError('SIMULATION_FAILED', 'final_signed_simulation', 'This swap no longer passes GASLESS safety checks. Nothing was submitted.');
      broadcastAttempted = true; const submitted = await this.rpc.sendRawTransaction(fullySigned); signature = submitted.signature; swap.signature = signature; swap.status = 'submitted'; quote.status = 'submitted'; const submittedAt = new Date().toISOString(); await this.durable.updateTransaction(swap.prepared.transactionId, { status: 'submitted', signature, submittedAt, updatedAt: submittedAt }); await this.durable.appendEvent(swap.prepared.transactionId, 'swap_submitted', 'submitted', { signature, provider: submitted.provider }, `${swap.prepared.transactionId}:submitted`); await this.persistQuote(quote); return this.resumeSubmitted(quote, false);
    } catch (error) { const normalized = asGaslessError(error, 'swap_submit', input.requestId); const failure = koraFailure(normalized); if (!crossed) for (const key of acquired) await this.temporary.releaseReplayLockIfSafe(key, input.requestId); if (failure) { const metadata = { transactionId: swap.prepared.transactionId, intentId: quote.intent.intentId, quoteId: quote.quoteId, messageHash: swap.prepared.preparedMessageHash, httpStatus: failure.httpStatus, koraRpcCode: failure.rpcCode, category: failure.category, reason: failure.reason, payerSignatureReturned: failure.payerSignatureReturned || payerSigned, broadcastAttempted }; await this.durable.appendEvent(swap.prepared.transactionId, 'kora_rejected', 'relayer', metadata, `${swap.prepared.transactionId}:kora:${failure.category}`).catch(() => undefined); log('error', 'kora_rejected', metadata); if (canReleaseAfterKoraFailure(failure, { payerSigned, signature, broadcastAttempted }) && this.risk) { try { await this.durable.appendEvent(swap.prepared.transactionId, 'sponsorship_release_authorized', 'sponsorship_release', { quoteId: quote.quoteId, amountLamports: swap.sponsoredCostLamports, category: failure.category }, `${swap.prepared.transactionId}:sponsorship_release_authorized`); const release = await this.risk.releaseQuoteExposure(quote); await this.durable.appendEvent(swap.prepared.transactionId, 'sponsorship_reservation_released', 'sponsorship_release', { quoteId: quote.quoteId, amountLamports: swap.sponsoredCostLamports, result: release }, `${swap.prepared.transactionId}:sponsorship_released`); } catch { log('error', 'sponsorship_release_failed', { transactionId: swap.prepared.transactionId, quoteId: quote.quoteId }); } } } if (!signature) { swap.status = crossed ? 'failed' : 'awaiting_user_signature'; quote.status = swap.status; await this.persistQuote(quote).catch(() => undefined); await this.durable.updateTransaction(swap.prepared.transactionId, { status: swap.status, failedAt: crossed ? new Date().toISOString() : undefined, errorCode: normalized.code, errorStage: normalized.stage, updatedAt: new Date().toISOString() }).catch(() => undefined); } await this.durable.appendEvent(swap.prepared.transactionId, 'swap_failed', normalized.stage, { code: normalized.code }, `${swap.prepared.transactionId}:failed:${normalized.code}`).catch(() => undefined); log('error', 'swap_rejected', { requestId: input.requestId, quoteId: input.quoteId, code: normalized.code, stage: normalized.stage }); throw normalized; }
  }

  private details(source: NonNullable<ReturnType<typeof inspectSendTokenAccount>>, input: TokenRegistryEntry, output: TokenRegistryEntry, outputAccount: string, exists: boolean, total: bigint, routed: bigint, fee: bigint, reimbursement: bigint, rent: bigint, slippage: number, build: JupiterBuild, reimbursementDestination: string, serviceFeeDestination: string): SwapQuoteDetails { return { schemaVersion: 'swap-v1', inputToken: { ...source, swapInputEnabled: true, swapOutputEnabled: input.swapOutputEnabled === true }, outputToken: { mint: output.mint, symbol: output.symbol, decimals: output.decimals, tokenProgram: output.tokenProgram, swapInputEnabled: output.swapInputEnabled === true, swapOutputEnabled: true }, outputAccount, outputAtaExists: exists, totalInputRaw: total.toString(), routedInputRaw: routed.toString(), expectedOutputRaw: build.outAmount, minimumOutputRaw: build.otherAmountThreshold, serviceFeeBps: this.policy.serviceFeeBps, serviceFeeRaw: fee.toString(), sponsorReimbursementRaw: reimbursement.toString(), outputAtaRentLamports: rent.toString(), slippageBps: slippage, priceImpactBps: parsePriceImpactBps(build.priceImpactPct), routeLabel: build.routePlan.map((step) => step.swapInfo?.label).filter(Boolean).join(' → ') || 'Jupiter', routeFingerprint: routeFingerprint(build), reimbursementDestination, serviceFeeDestination, status: 'created', route: build }; }
  private approvedDexFamilies(input: TokenRegistryEntry, output: TokenRegistryEntry) { const left = input.approvedDexFamilies?.length ? input.approvedDexFamilies : [RAYDIUM_CLMM_DEX]; const right = output.approvedDexFamilies?.length ? output.approvedDexFamilies : [RAYDIUM_CLMM_DEX]; const result = APPROVED_DEX_FAMILIES.filter((family) => left.includes(family) && right.includes(family)); if (!result.length) throw new GaslessError('TOKEN_UNSUPPORTED', 'swap_route_policy', 'This token pair has no approved GASLESS route family.'); return result; }
  private async buildRoute(input: { inputMint: string; outputMint: string; amount: string; taker: string; payer: string; outputAccount: string; slippageBps: number }, families: readonly ApprovedDexFamily[]) { const currentBlockHeight = await this.rpc.getBlockHeight(); const buildOne = async (family: ApprovedDexFamily) => { const build = await this.jupiter.build({ inputMint: input.inputMint, outputMint: input.outputMint, amount: input.amount, taker: input.taker, payer: input.payer, destinationTokenAccount: input.outputAccount, slippageBps: input.slippageBps, dexes: [family] }); this.jupiter.validate(build, { inputMint: input.inputMint, outputMint: input.outputMint, outputAccount: input.outputAccount, amount: input.amount, taker: input.taker, payer: input.payer, slippageBps: input.slippageBps, dexes: [family], maxPriceImpactBps: this.policy.maximumPriceImpactBps }, currentBlockHeight); return { family, build }; }; if (families.length === 1) return buildOne(families[0]!); const candidates = await Promise.allSettled(families.map(buildOne)); const valid = candidates.flatMap((candidate) => candidate.status === 'fulfilled' ? [candidate.value] : []).sort((left, right) => BigInt(right.build.outAmount) > BigInt(left.build.outAmount) ? 1 : BigInt(right.build.outAmount) < BigInt(left.build.outAmount) ? -1 : 0); if (!valid.length) throw new GaslessError('TOKEN_UNSUPPORTED', 'swap_route_policy', 'No approved GASLESS route is available for this pair right now.'); return valid[0]!; }
  private async requireEntry(mint: string, direction: 'input' | 'output') { const result = await this.registry.evaluate('SWAP', mint); const entry = result.entry; const capability = direction === 'input' ? 'SWAP_INPUT' : 'SWAP_OUTPUT'; if (result.decision === 'blocked' || entry?.pausedCapabilities?.includes(capability)) throw new GaslessError('TOKEN_PAUSED', `swap_${direction}_token`, 'This token is temporarily unavailable for this action.'); if (result.decision !== 'supported' || !entry || (direction === 'input' ? !entry.feePaymentEnabled || !entry.swapInputEnabled : !entry.swapOutputEnabled)) throw new GaslessError('TOKEN_UNSUPPORTED', `swap_${direction}_token`, `This token is not available as a swap ${direction}.`); return entry; }
  private async activeEntries() { return (await this.registry.list('SWAP')).filter((entry) => { try { new PublicKey(entry.mint); return entry.tokenProgram === 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' && !entry.extensions.length && Number.isInteger(entry.decimals) && entry.decimals >= 1 && entry.decimals <= 9; } catch { return false; } }); }
  private assertPolicy(input: TokenRegistryEntry, output: TokenRegistryEntry) { try { for (const entry of [input, output]) { new PublicKey(entry.mint); if (entry.tokenProgram !== 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' || entry.extensions.length || !Number.isInteger(entry.decimals) || entry.decimals < 1 || entry.decimals > 9) throw new Error(); } for (const address of [this.policy.reimbursementWallet, this.policy.serviceFeeWallet]) new PublicKey(address!); const priceTime = Date.parse(input.priceUpdatedAt ?? ''); if (BigInt(input.usdPriceMicros ?? '0') <= 0n || BigInt(input.solUsdPriceMicros ?? '0') <= 0n || !Number.isFinite(priceTime) || Date.now() - priceTime > this.policy.priceMaxAgeSeconds * 1000 || Date.now() - priceTime < -30_000 || !Number.isSafeInteger(this.policy.maximumSponsoredCostLamports) || this.policy.maximumSponsoredCostLamports <= 0 || !Number.isSafeInteger(this.policy.maximumPriceImpactBps) || this.policy.maximumPriceImpactBps < 0) throw new Error(); } catch { throw new GaslessError('TOKEN_UNSUPPORTED', 'swap_policy', "We can't calculate a safe gasless swap for this pair right now."); } }
  private assertDestinations(wallet: string) { if (!this.policy.reimbursementWallet || !this.policy.serviceFeeWallet || wallet === this.policy.reimbursementWallet || wallet === this.policy.serviceFeeWallet) throw new GaslessError('CONFIGURATION_ERROR', 'swap_configuration', 'The user and GASLESS settlement wallet must be separate.'); }
  private async requireSettlementAccounts(entry: TokenRegistryEntry) { const reimbursementDestination = deriveAssociatedTokenAddress(this.policy.reimbursementWallet!, entry.mint, entry.tokenProgram); const serviceFeeDestination = deriveAssociatedTokenAddress(this.policy.serviceFeeWallet!, entry.mint, entry.tokenProgram); for (const [address, owner] of [[reimbursementDestination, this.policy.reimbursementWallet!], [serviceFeeDestination, this.policy.serviceFeeWallet!]] as const) { try { if (!validateDestinationAccount(await this.rpc.getAccountInfo(address), owner, entry.mint, address)) throw new Error(); } catch { throw new GaslessError('CONFIGURATION_ERROR', 'swap_configuration', 'GASLESS Swap settlement accounts are not configured for this input token.'); } } return { reimbursementDestination, serviceFeeDestination }; }
  private refreshRequired() { return new GaslessError('QUOTE_EXPIRED', 'swap_pre_sign', 'Price refreshed. Review the updated amounts before continuing.'); }
  private async priced(entry: TokenRegistryEntry) { if (!this.prices) return entry; const prices = await this.prices.getUsdPrices([entry.mint]); const token = prices[entry.mint]!; const sol = prices[WRAPPED_SOL_MINT]!; return { ...entry, usdPriceMicros: token.usdPriceMicros, solUsdPriceMicros: sol.usdPriceMicros, priceUpdatedAt: token.observedAt < sol.observedAt ? token.observedAt : sol.observedAt }; }
  private async recheck(swap: SwapQuoteDetails, wallet: string) { const input = await this.requireEntry(swap.inputToken.mint, 'input'); await this.requireEntry(swap.outputToken.mint, 'output'); try { this.assertPolicy({ ...input, usdPriceMicros: '1', solUsdPriceMicros: '1', priceUpdatedAt: new Date().toISOString() }, input); } catch { throw new GaslessError('TOKEN_UNSUPPORTED', 'swap_policy', 'This token is temporarily unavailable.'); } await this.requireSettlementAccounts(input); const source = inspectSendTokenAccount(swap.inputToken.sourceAccount, await this.rpc.getAccountInfo(swap.inputToken.sourceAccount), wallet, input); if (!source || BigInt(source.balanceRaw) < BigInt(swap.totalInputRaw)) throw new GaslessError('INSUFFICIENT_BALANCE', 'swap_state_recheck', 'Your token balance changed. Refresh the swap quote.'); const output = await this.rpc.getAccountInfo(swap.outputAccount); if (output) { try { validateDestinationAccount(output, wallet, swap.outputToken.mint, swap.outputAccount); } catch { throw new GaslessError('MESSAGE_MISMATCH', 'swap_state_recheck', 'Your receiving token account changed. Refresh the swap quote.'); } } else if (swap.outputAtaExists) throw new GaslessError('MESSAGE_MISMATCH', 'swap_state_recheck', 'Your receiving token account changed. Refresh the swap quote.'); }
  private async resumeSubmitted(quote: TransactionQuote, alreadyCompleted = true) { const swap = quote.swap!; const confirmation = await this.confirm(swap.signature!, swap.prepared!.lastValidBlockHeight); const reconciliation = await this.reconcile(quote, confirmation); swap.reconciliation = reconciliation; swap.status = reconciliation.status === 'confirmed' ? 'reconciled' : reconciliation.status === 'failed' ? 'failed' : 'submitted'; quote.status = swap.status; await this.persistQuote(quote); await this.durable.updateIntentStatus(quote.intent.intentId, quote.status); if (reconciliation.status !== 'confirmed') throw new GaslessError('RECONCILIATION_FAILED', 'reconciliation', 'This swap was submitted and is still being verified.', true); return { transactionId: swap.prepared!.transactionId, signature: swap.signature!, confirmation, reconciliation, alreadyCompleted }; }
  private async confirm(signature: string, lastValidBlockHeight: number) { const deadline = Date.now() + 35_000; while (Date.now() < deadline) { const status = await this.rpc.getSignatureStatuses(signature); if (status?.err) return { signature, outcome: 'confirmed_chain_error' as const }; if (status?.confirmationStatus === 'confirmed' || status?.confirmationStatus === 'finalized') return { signature, outcome: 'confirmed_success' as const }; if (await this.rpc.getBlockHeight() > lastValidBlockHeight) return { signature, outcome: 'expired' as const }; await new Promise((resolve) => setTimeout(resolve, 1_000)); } return { signature, outcome: 'timeout_unknown' as const }; }
  private async reconcile(quote: TransactionQuote, confirmation: { signature: string; outcome: string }): Promise<ReconciliationResult> { const swap = quote.swap!; const id = swap.prepared!.transactionId; const now = new Date().toISOString(); if (confirmation.outcome !== 'confirmed_success') return { transactionId: id, signature: confirmation.signature, status: confirmation.outcome === 'confirmed_chain_error' ? 'failed' : 'pending', reconciledAt: now }; const chain = await this.rpc.getTransaction(confirmation.signature); if (!chain || chain.meta.err !== null) return { transactionId: id, signature: confirmation.signature, status: chain ? 'failed' : 'pending', reconciledAt: now }; const addresses = chain.transaction.message.accountKeys.map(String); const raw = (items: NonNullable<typeof chain.meta.postTokenBalances>, address: string, mint: string) => items.find((item) => item.accountIndex === addresses.indexOf(address) && item.mint === mint)?.uiTokenAmount.amount; const delta = (address: string, mint: string) => BigInt(raw(chain.meta.postTokenBalances ?? [], address, mint) ?? '0') - BigInt(raw(chain.meta.preTokenBalances ?? [], address, mint) ?? '0'); const inputDebit = BigInt(swap.totalInputRaw); const output = delta(swap.outputAccount, swap.outputToken.mint); const payerIndex = addresses.indexOf(swap.prepared!.expectedFeePayer); const payerDelta = payerIndex < 0 ? 0n : BigInt(chain.meta.postBalances[payerIndex]) - BigInt(chain.meta.preBalances[payerIndex]); const expected = new Map<string, bigint>(); for (const [address, value] of [[swap.reimbursementDestination, BigInt(swap.sponsorReimbursementRaw)], [swap.serviceFeeDestination, BigInt(swap.serviceFeeRaw)]] as const) expected.set(address, (expected.get(address) ?? 0n) + value); const valid = delta(swap.inputToken.sourceAccount, swap.inputToken.mint) === -inputDebit && [...expected].every(([address, value]) => delta(address, swap.inputToken.mint) === value) && output >= BigInt(swap.minimumOutputRaw) && payerDelta === -BigInt(swap.sponsoredCostLamports!); const status = valid ? 'confirmed' : 'failed'; const result: ReconciliationResult = { transactionId: id, signature: confirmation.signature, status, networkFeeLamports: String(chain.meta.fee), reconciledAt: now }; await this.durable.updateTransaction(id, { status: valid ? 'reconciled' : 'failed', confirmedAt: valid ? now : undefined, failedAt: valid ? undefined : now, errorCode: valid ? undefined : 'RECONCILIATION_FAILED', errorStage: valid ? undefined : 'swap_economics', updatedAt: now, actualOutputRaw: output.toString() }); if (valid) { const record = await this.durable.getTransaction(id); if (!record) throw new GaslessError('RECONCILIATION_FAILED', 'reconciliation', 'Swap accounting record was not found.'); await this.durable.recordSwapAccounting(record, String(chain.meta.fee), output.toString()); await this.releaseSuccessfulExposure(quote); } return result; }
  private async releaseSuccessfulExposure(quote: TransactionQuote) { const swap = quote.swap; const prepared = swap?.prepared; if (!this.risk || !swap || !prepared) return; const id = prepared.transactionId; try { await this.durable.appendEvent(id, 'sponsorship_release_authorized', 'sponsorship_release', { quoteId: quote.quoteId, amountLamports: swap.sponsoredCostLamports, reason: 'reconciled_success' }, `${id}:success_sponsorship_release_authorized`); const release = await this.risk.releaseQuoteExposure(quote); await this.durable.appendEvent(id, 'sponsorship_reservation_released', 'sponsorship_release', { quoteId: quote.quoteId, amountLamports: swap.sponsoredCostLamports, result: release }, `${id}:success_sponsorship_released`); } catch { log('error', 'sponsorship_release_failed', { transactionId: id, quoteId: quote.quoteId, reason: 'reconciled_success' }); } }
  private async requireQuote(id: string, wallet: string, allowFinished = false) { const quote = await this.temporary.getQuote(id); if (!quote?.swap) throw new GaslessError('QUOTE_NOT_FOUND', 'swap_quote', 'This swap quote was not found.'); if (quote.intent.walletAddress !== wallet) throw new GaslessError('SESSION_ERROR', 'swap_quote', 'This swap quote belongs to a different wallet.'); if (!['submitted', 'reconciled'].includes(quote.swap.status) && !await this.temporary.isAuthoritativeSwapQuote(this.authorityKey(quote.intent.network, wallet), id)) throw this.refreshRequired(); if (Date.parse(quote.expiresAt) <= Date.now() && !['submitted', 'reconciled'].includes(quote.swap.status)) throw new GaslessError('QUOTE_EXPIRED', 'swap_quote', 'The price changed while you were reviewing the swap. Refresh your quote.'); if (!allowFinished && ['failed', 'reconciled'].includes(quote.status)) throw new GaslessError('QUOTE_ALREADY_USED', 'swap_quote', 'This swap quote has already finished.'); return quote; }
  private authorityKey(network: SolanaNetwork, wallet: string) { return `${network}:${wallet}`; }
  private persistQuote(quote: TransactionQuote) { return this.temporary.saveQuote(quote, quote.status === 'reconciled' ? 86_400 : Math.max(1, Math.ceil((Date.parse(quote.expiresAt) - Date.now()) / 1000))); }
}
